// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: graphiti.proto

package graphitiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestEpisodeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content           string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Source            string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // "message", "document", "event"
	SourceDescription string                 `protobuf:"bytes,4,opt,name=source_description,json=sourceDescription,proto3" json:"source_description,omitempty"`
	ReferenceTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reference_time,json=referenceTime,proto3" json:"reference_time,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IngestEpisodeRequest) Reset() {
	*x = IngestEpisodeRequest{}
	mi := &file_graphiti_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEpisodeRequest) ProtoMessage() {}

func (x *IngestEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEpisodeRequest.ProtoReflect.Descriptor instead.
func (*IngestEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEpisodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngestEpisodeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IngestEpisodeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestEpisodeRequest) GetSourceDescription() string {
	if x != nil {
		return x.SourceDescription
	}
	return ""
}

func (x *IngestEpisodeRequest) GetReferenceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReferenceTime
	}
	return nil
}

func (x *IngestEpisodeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestEpisodeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId       string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	EntitiesCreated int32                  `protobuf:"varint,2,opt,name=entities_created,json=entitiesCreated,proto3" json:"entities_created,omitempty"`
	EdgesCreated    int32                  `protobuf:"varint,3,opt,name=edges_created,json=edgesCreated,proto3" json:"edges_created,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestEpisodeResponse) Reset() {
	*x = IngestEpisodeResponse{}
	mi := &file_graphiti_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEpisodeResponse) ProtoMessage() {}

func (x *IngestEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEpisodeResponse.ProtoReflect.Descriptor instead.
func (*IngestEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEpisodeResponse) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *IngestEpisodeResponse) GetEntitiesCreated() int32 {
	if x != nil {
		return x.EntitiesCreated
	}
	return 0
}

func (x *IngestEpisodeResponse) GetEdgesCreated() int32 {
	if x != nil {
		return x.EdgesCreated
	}
	return 0
}

func (x *IngestEpisodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GraphSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	EntityTypes   []string               `protobuf:"bytes,3,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	CenterDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=center_date,json=centerDate,proto3" json:"center_date,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphSearchRequest) Reset() {
	*x = GraphSearchRequest{}
	mi := &file_graphiti_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSearchRequest) ProtoMessage() {}

func (x *GraphSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSearchRequest.ProtoReflect.Descriptor instead.
func (*GraphSearchRequest) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{2}
}

func (x *GraphSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GraphSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GraphSearchRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *GraphSearchRequest) GetCenterDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CenterDate
	}
	return nil
}

func (x *GraphSearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GraphSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Episodes      []*Episode             `protobuf:"bytes,3,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphSearchResponse) Reset() {
	*x = GraphSearchResponse{}
	mi := &file_graphiti_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSearchResponse) ProtoMessage() {}

func (x *GraphSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSearchResponse.ProtoReflect.Descriptor instead.
func (*GraphSearchResponse) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{3}
}

func (x *GraphSearchResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphSearchResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *GraphSearchResponse) GetEpisodes() []*Episode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_graphiti_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeRequest) Reset() {
	*x = GetEdgeRequest{}
	mi := &file_graphiti_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeRequest) ProtoMessage() {}

func (x *GetEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeRequest.ProtoReflect.Descriptor instead.
func (*GetEdgeRequest) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{5}
}

func (x *GetEdgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_graphiti_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{6}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Node) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Node) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Relation      string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Fact          string                 `protobuf:"bytes,5,opt,name=fact,proto3" json:"fact,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_graphiti_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{7}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Edge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Edge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Edge) GetFact() string {
	if x != nil {
		return x.Fact
	}
	return ""
}

func (x *Edge) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Edge) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type Episode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	ReferenceTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reference_time,json=referenceTime,proto3" json:"reference_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_graphiti_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_graphiti_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_graphiti_proto_rawDescGZIP(), []int{8}
}

func (x *Episode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Episode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Episode) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Episode) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Episode) GetReferenceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReferenceTime
	}
	return nil
}

var File_graphiti_proto protoreflect.FileDescriptor

const file_graphiti_proto_rawDesc = "" +
	"\n" +
	"\x0egraphiti.proto\x12\x17vnp.gateway.graphiti.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x02\n" +
	"\x14IngestEpisodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12-\n" +
	"\x12source_description\x18\x04 \x01(\tR\x11sourceDescription\x12A\n" +
	"\x0ereference_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rreferenceTime\x12W\n" +
	"\bmetadata\x18\x06 \x03(\v2;.vnp.gateway.graphiti.v1.IngestEpisodeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x15IngestEpisodeResponse\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12)\n" +
	"\x10entities_created\x18\x02 \x01(\x05R\x0fentitiesCreated\x12#\n" +
	"\redges_created\x18\x03 \x01(\x05R\fedgesCreated\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xb0\x02\n" +
	"\x12GraphSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12!\n" +
	"\fentity_types\x18\x03 \x03(\tR\ventityTypes\x12;\n" +
	"\vcenter_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"centerDate\x12R\n" +
	"\afilters\x18\x05 \x03(\v28.vnp.gateway.graphiti.v1.GraphSearchRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x13GraphSearchResponse\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.vnp.gateway.graphiti.v1.NodeR\x05nodes\x123\n" +
	"\x05edges\x18\x02 \x03(\v2\x1d.vnp.gateway.graphiti.v1.EdgeR\x05edges\x12<\n" +
	"\bepisodes\x18\x03 \x03(\v2 .vnp.gateway.graphiti.v1.EpisodeR\bepisodes\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eGetEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12M\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2-.vnp.gateway.graphiti.v1.Node.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x01\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12\x12\n" +
	"\x04fact\x18\x05 \x01(\tR\x04fact\x129\n" +
	"\n" +
	"valid_from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\"\xa2\x01\n" +
	"\aEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12A\n" +
	"\x0ereference_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rreferenceTime2\x8a\x01\n" +
	"\x18GraphitiIngestionService\x12n\n" +
	"\rIngestEpisode\x12-.vnp.gateway.graphiti.v1.IngestEpisodeRequest\x1a..vnp.gateway.graphiti.v1.IngestEpisodeResponse2|\n" +
	"\x15GraphitiSearchService\x12c\n" +
	"\x06Search\x12+.vnp.gateway.graphiti.v1.GraphSearchRequest\x1a,.vnp.gateway.graphiti.v1.GraphSearchResponse2\xbc\x01\n" +
	"\x14GraphitiStoreService\x12Q\n" +
	"\aGetNode\x12'.vnp.gateway.graphiti.v1.GetNodeRequest\x1a\x1d.vnp.gateway.graphiti.v1.Node\x12Q\n" +
	"\aGetEdge\x12'.vnp.gateway.graphiti.v1.GetEdgeRequest\x1a\x1d.vnp.gateway.graphiti.v1.EdgeBKZIgithub.com/vnp-community/vnp-memory/gateway/gen/go/graphiti/v1;graphitiv1b\x06proto3"

var (
	file_graphiti_proto_rawDescOnce sync.Once
	file_graphiti_proto_rawDescData []byte
)

func file_graphiti_proto_rawDescGZIP() []byte {
	file_graphiti_proto_rawDescOnce.Do(func() {
		file_graphiti_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graphiti_proto_rawDesc), len(file_graphiti_proto_rawDesc)))
	})
	return file_graphiti_proto_rawDescData
}

var file_graphiti_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_graphiti_proto_goTypes = []any{
	(*IngestEpisodeRequest)(nil),  // 0: vnp.gateway.graphiti.v1.IngestEpisodeRequest
	(*IngestEpisodeResponse)(nil), // 1: vnp.gateway.graphiti.v1.IngestEpisodeResponse
	(*GraphSearchRequest)(nil),    // 2: vnp.gateway.graphiti.v1.GraphSearchRequest
	(*GraphSearchResponse)(nil),   // 3: vnp.gateway.graphiti.v1.GraphSearchResponse
	(*GetNodeRequest)(nil),        // 4: vnp.gateway.graphiti.v1.GetNodeRequest
	(*GetEdgeRequest)(nil),        // 5: vnp.gateway.graphiti.v1.GetEdgeRequest
	(*Node)(nil),                  // 6: vnp.gateway.graphiti.v1.Node
	(*Edge)(nil),                  // 7: vnp.gateway.graphiti.v1.Edge
	(*Episode)(nil),               // 8: vnp.gateway.graphiti.v1.Episode
	nil,                           // 9: vnp.gateway.graphiti.v1.IngestEpisodeRequest.MetadataEntry
	nil,                           // 10: vnp.gateway.graphiti.v1.GraphSearchRequest.FiltersEntry
	nil,                           // 11: vnp.gateway.graphiti.v1.Node.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_graphiti_proto_depIdxs = []int32{
	12, // 0: vnp.gateway.graphiti.v1.IngestEpisodeRequest.reference_time:type_name -> google.protobuf.Timestamp
	9,  // 1: vnp.gateway.graphiti.v1.IngestEpisodeRequest.metadata:type_name -> vnp.gateway.graphiti.v1.IngestEpisodeRequest.MetadataEntry
	12, // 2: vnp.gateway.graphiti.v1.GraphSearchRequest.center_date:type_name -> google.protobuf.Timestamp
	10, // 3: vnp.gateway.graphiti.v1.GraphSearchRequest.filters:type_name -> vnp.gateway.graphiti.v1.GraphSearchRequest.FiltersEntry
	6,  // 4: vnp.gateway.graphiti.v1.GraphSearchResponse.nodes:type_name -> vnp.gateway.graphiti.v1.Node
	7,  // 5: vnp.gateway.graphiti.v1.GraphSearchResponse.edges:type_name -> vnp.gateway.graphiti.v1.Edge
	8,  // 6: vnp.gateway.graphiti.v1.GraphSearchResponse.episodes:type_name -> vnp.gateway.graphiti.v1.Episode
	12, // 7: vnp.gateway.graphiti.v1.Node.created_at:type_name -> google.protobuf.Timestamp
	11, // 8: vnp.gateway.graphiti.v1.Node.attributes:type_name -> vnp.gateway.graphiti.v1.Node.AttributesEntry
	12, // 9: vnp.gateway.graphiti.v1.Edge.valid_from:type_name -> google.protobuf.Timestamp
	12, // 10: vnp.gateway.graphiti.v1.Edge.valid_to:type_name -> google.protobuf.Timestamp
	12, // 11: vnp.gateway.graphiti.v1.Episode.reference_time:type_name -> google.protobuf.Timestamp
	0,  // 12: vnp.gateway.graphiti.v1.GraphitiIngestionService.IngestEpisode:input_type -> vnp.gateway.graphiti.v1.IngestEpisodeRequest
	2,  // 13: vnp.gateway.graphiti.v1.GraphitiSearchService.Search:input_type -> vnp.gateway.graphiti.v1.GraphSearchRequest
	4,  // 14: vnp.gateway.graphiti.v1.GraphitiStoreService.GetNode:input_type -> vnp.gateway.graphiti.v1.GetNodeRequest
	5,  // 15: vnp.gateway.graphiti.v1.GraphitiStoreService.GetEdge:input_type -> vnp.gateway.graphiti.v1.GetEdgeRequest
	1,  // 16: vnp.gateway.graphiti.v1.GraphitiIngestionService.IngestEpisode:output_type -> vnp.gateway.graphiti.v1.IngestEpisodeResponse
	3,  // 17: vnp.gateway.graphiti.v1.GraphitiSearchService.Search:output_type -> vnp.gateway.graphiti.v1.GraphSearchResponse
	6,  // 18: vnp.gateway.graphiti.v1.GraphitiStoreService.GetNode:output_type -> vnp.gateway.graphiti.v1.Node
	7,  // 19: vnp.gateway.graphiti.v1.GraphitiStoreService.GetEdge:output_type -> vnp.gateway.graphiti.v1.Edge
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_graphiti_proto_init() }
func file_graphiti_proto_init() {
	if File_graphiti_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graphiti_proto_rawDesc), len(file_graphiti_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_graphiti_proto_goTypes,
		DependencyIndexes: file_graphiti_proto_depIdxs,
		MessageInfos:      file_graphiti_proto_msgTypes,
	}.Build()
	File_graphiti_proto = out.File
	file_graphiti_proto_goTypes = nil
	file_graphiti_proto_depIdxs = nil
}
