#!/usr/bin/env python3
"""
02_load_data.py — Load seed data and push to VNP Memory server via backend API.

Reads fixtures from ./data/*.json (generated by 01_generate_data.py).
Auth and server settings are read from .env.

Usage:
    python 02_load_data.py [--engine ENGINE]

Options:
    --engine  Only run the specified engine loader:
              admin | cognee | graphiti | memobase | zep | sm | agent | observe | ov | all
              Default: all

Reference API:
    specs/backend-api-specs.md
"""

from __future__ import annotations

import argparse
import sys
import time

from client import api, cfg, load_json, save_json, print_section

# Keeps track of IDs created for use by later loaders
CREATED: dict = {}


# ── 1. Admin ──────────────────────────────────────────────────────────────────

def load_admin() -> None:
    print_section("1. Admin — Create Tenant & API Key")
    data = load_json("admin.json")

    # POST /v1/admin/tenants
    tenant = data["tenant"]
    result = api.safe_post("/v1/admin/tenants", {
        "name": tenant["name"],
        "slug": tenant["slug"],
        "plan": tenant["plan"],
    })
    if result:
        tid = result.get("id") or tenant["id"]
        CREATED["tenant_id"] = tid
        print(f"  ✓ Tenant created: {tid}")

        # Issue API key POST /v1/admin/tenants/{id}/keys
        key_result = api.safe_post(f"/v1/admin/tenants/{tid}/keys", {
            "name": data["api_key"]["name"],
        })
        if key_result:
            CREATED["api_key"] = key_result.get("key") or key_result.get("key_prefix", "?")
            print(f"  ✓ API key issued: {CREATED['api_key'][:20]}...")
    else:
        print("  ⚠ Tenant creation skipped (may already exist)")
        CREATED["tenant_id"] = tenant["id"]

    save_json("created_admin.json", {"tenant_id": CREATED.get("tenant_id")})


# ── 2. Cognee ─────────────────────────────────────────────────────────────────

def load_cognee() -> None:
    print_section("2. Cognee — Datasets, Data Upload & Cognify")
    data = load_json("cognee.json")
    created_datasets = []

    for ds in data["datasets"]:
        # Create dataset: POST /v1/cognee/datasets
        result = api.safe_post("/v1/cognee/datasets", {"name": ds["name"]})
        if not result:
            print(f"  ✗ Failed to create dataset '{ds['name']}'")
            continue

        ds_id = result.get("id") or result.get("dataset_id", "unknown")
        print(f"  ✓ Dataset created: {ds['name']} ({ds_id})")

        # Upload data items: POST /v1/cognee/datasets/{id}/data
        items_ok = 0
        for item in ds["data_items"]:
            r = api.safe_post(f"/v1/cognee/datasets/{ds_id}/data", {
                "dataset_id": ds_id,
                "content_type": item["content_type"],
                "content": item["content"].encode() if isinstance(item["content"], str) else item["content"],
                "metadata": item.get("metadata", {}),
                "node_sets": item.get("node_sets", []),
            })
            if r:
                items_ok += 1
        print(f"    ↳ {items_ok}/{len(ds['data_items'])} data items uploaded")

        # Trigger cognify: POST /v1/cognee/datasets/{id}/cognify
        cognify_result = api.safe_post(f"/v1/cognee/datasets/{ds_id}/cognify", {
            "dataset_id": ds_id,
            **ds["cognify_config"],
        })
        if cognify_result:
            job_id = cognify_result.get("job_id", "?")
            print(f"    ↳ Cognify job started: {job_id}")

        created_datasets.append({"name": ds["name"], "id": ds_id})

    CREATED["cognee_datasets"] = created_datasets
    save_json("created_cognee.json", created_datasets)


# ── 3. Graphiti ───────────────────────────────────────────────────────────────

def load_graphiti() -> None:
    print_section("3. Graphiti — Episode Ingestion & Ontology")
    data = load_json("graphiti.json")
    created_episodes = []

    # Set ontology: POST /v1/zep/graph/ontology (shared by graphiti backend)
    onto_result = api.safe_post("/v1/graphiti/ontology", data["ontology"])
    if onto_result:
        print(f"  ✓ Ontology set ({len(data['ontology']['entity_types'])} entity types)")

    # Ingest episodes: POST /v1/graphiti/episodes
    ok_count = 0
    for ep in data["episodes"]:
        result = api.safe_post("/v1/graphiti/episodes", ep)
        if result:
            episode_id = result.get("uuid") or result.get("id", "?")
            created_episodes.append({"name": ep["name"], "id": episode_id})
            ok_count += 1
        else:
            print(f"  ✗ Failed: {ep['name']}")

    print(f"  ✓ {ok_count}/{len(data['episodes'])} episodes ingested")
    CREATED["graphiti_episodes"] = created_episodes
    save_json("created_graphiti.json", created_episodes)


# ── 4. Memobase ───────────────────────────────────────────────────────────────

def load_memobase() -> None:
    print_section("4. Memobase — Users, Blobs & Flush")
    data = load_json("memobase.json")
    created_users = []

    for user in data["users"]:
        uid = user["user_id"]
        print(f"  • User: {uid}")

        # Insert blobs: POST /v1/memobase/users/{uid}/blobs
        ok_count = 0
        for blob in user["blobs"]:
            r = api.safe_post(f"/v1/memobase/users/{uid}/blobs", blob)
            if r:
                ok_count += 1
        print(f"    ↳ {ok_count}/{len(user['blobs'])} blobs inserted")

        # Flush: POST /v1/memobase/users/{uid}/flush
        flush_result = api.safe_post(f"/v1/memobase/users/{uid}/flush", {})
        if flush_result:
            print(f"    ↳ Buffer flushed")

        created_users.append(uid)

    CREATED["memobase_users"] = created_users
    save_json("created_memobase.json", created_users)


# ── 5. Zep ────────────────────────────────────────────────────────────────────

def load_zep() -> None:
    print_section("5. Zep — Users, Threads & Messages")
    data = load_json("zep.json")
    created_users = []

    for user in data["users"]:
        uid = user["user_id"]

        # Create user: POST /v1/zep/users
        result = api.safe_post("/v1/zep/users", {
            "user_id": uid,
            "email": user["email"],
            "first_name": user["first_name"],
            "last_name": user["last_name"],
            "metadata": user["metadata"],
        })
        if result:
            print(f"  ✓ Zep user created: {uid}")
        else:
            # User may already exist — try to patch metadata
            api.safe_post(f"/v1/zep/users/{uid}", {"metadata": user["metadata"]})
            print(f"  ~ Zep user {uid} patched (already existed)")

        # Ingest sessions/messages
        for sess in user["sessions"]:
            sess_id = sess["session_id"]
            # PUT memory: POST /v1/zep/sessions/{id}/memory
            memory_result = api.safe_post(f"/v1/zep/sessions/{sess_id}/memory", {
                "messages": sess["messages"],
            })
            if memory_result:
                print(f"    ↳ Session {sess_id}: {len(sess['messages'])} messages ingested")

        created_users.append(uid)

    CREATED["zep_users"] = created_users
    save_json("created_zep.json", created_users)


# ── 6. Supermemory ────────────────────────────────────────────────────────────

def load_supermemory() -> None:
    print_section("6. Supermemory — Memories & Documents")
    data = load_json("supermemory.json")
    created_memories = []
    created_docs = []

    # Create memories: POST /v1/sm/memories
    for mem in data["memories"]:
        result = api.safe_post("/v1/sm/memories", mem)
        if result:
            created_memories.append(result.get("id", "?"))

    print(f"  ✓ {len(created_memories)}/{len(data['memories'])} memories created")

    # Create documents: POST /v1/sm/documents
    for doc in data["documents"]:
        result = api.safe_post("/v1/sm/documents", doc)
        if result:
            created_docs.append({"id": result.get("id", "?"), "title": doc["title"]})
            print(f"    ↳ Document: {doc['title']}")

    CREATED["sm_memories"] = created_memories
    CREATED["sm_documents"] = created_docs
    save_json("created_supermemory.json", {
        "memories": created_memories,
        "documents": created_docs,
    })


# ── 7. Agent Memory ───────────────────────────────────────────────────────────

def load_agent_memory() -> None:
    print_section("7. Agent Memory — Remember & Slots")
    data = load_json("agent_memory.json")
    created_ids = []

    # Store agent memories: POST /v1/memory/agent/remember
    for mem in data["memories"]:
        result = api.safe_post("/v1/memory/agent/remember", mem)
        if result:
            mem_id = result.get("id", "?")
            created_ids.append(mem_id)

    print(f"  ✓ {len(created_ids)}/{len(data['memories'])} agent memories stored")

    # Write memory slots: POST /v1/memory/slots/{scope}/{label}
    for slot in data["slots"]:
        scope = slot["scope"]
        label = slot["label"]
        result = api.safe_post(f"/v1/memory/slots/{scope}/{label}", {
            "content": slot["content"],
            "description": slot.get("description", ""),
            "size_limit": slot.get("size_limit", 4096),
            "pinned": slot.get("pinned", False),
        })
        if result:
            print(f"  ✓ Slot written: {scope}/{label}")

    CREATED["agent_memories"] = created_ids
    save_json("created_agent_memory.json", created_ids)


# ── 8. Observe Sessions ───────────────────────────────────────────────────────

def load_observe() -> None:
    print_section("8. Observe — Sessions & Observations")
    data = load_json("observe.json")
    created_sessions = []

    for sess_data in data["sessions"]:
        # Start session: POST /v1/observe/sessions
        result = api.safe_post("/v1/observe/sessions", {
            "project": sess_data["project"],
            "cwd": sess_data["cwd"],
            "model": sess_data["model"],
            "agent_id": sess_data["agent_id"],
        })
        if not result:
            print(f"  ✗ Failed to create observe session for {sess_data['project']}")
            continue

        sess_id = result.get("id", "?")
        print(f"  ✓ Observe session started: {sess_id}")

        # Add observations: POST /v1/observe/sessions/{id}/observe
        obs_ok = 0
        for obs in sess_data["observations"]:
            r = api.safe_post(f"/v1/observe/sessions/{sess_id}/observe", obs)
            if r:
                obs_ok += 1

        print(f"    ↳ {obs_ok}/{len(sess_data['observations'])} observations added")

        # End session: POST /v1/observe/sessions/{id}/end
        end_result = api.safe_post(f"/v1/observe/sessions/{sess_id}/end", {
            "tags": sess_data.get("tags", []),
        })
        if end_result:
            print(f"    ↳ Session ended")

        created_sessions.append(sess_id)

    CREATED["observe_sessions"] = created_sessions
    save_json("created_observe.json", created_sessions)


# ── 9. OpenViking ─────────────────────────────────────────────────────────────

def load_openviking() -> None:
    print_section("9. OpenViking — Files, Resource & Session")
    data = load_json("openviking.json")
    created_files = []

    # Write files: PUT /v1/ov/files/{path}
    for f in data["files"]:
        path = f["path"]
        result = api.safe_post(f"/v1/ov/files{path}",  # using safe_post as a convenience
                               None,
                               data=f["content"].encode(),
                               headers={"Content-Type": f.get("mime_type", "text/plain")})
        # Actually use PUT
        try:
            resp = api._request(
                "PUT",
                f"/v1/ov/files{path}",
                data=f["content"].encode(),
                headers={"Content-Type": f.get("mime_type", "text/plain")},
            )
            if resp.status_code in (200, 201, 204):
                created_files.append(path)
                print(f"  ✓ File written: {path}")
            else:
                print(f"  ✗ File failed {path}: {resp.status_code}")
        except Exception as exc:
            print(f"  ✗ File error {path}: {exc}")

    # Ingest resource: POST /v1/ov/resources/ingest
    res = data["resource"]
    result = api.safe_post("/v1/ov/resources/ingest", {
        "uri": res["uri"],
        "type": res["type"],
        "options": res["options"],
    })
    if result:
        print(f"  ✓ Resource ingested: {res['uri']}")

    # Create session: POST /v1/ov/sessions
    sess = data["session"]
    result = api.safe_post("/v1/ov/sessions", sess)
    if result:
        sess_id = result.get("id", "?")
        print(f"  ✓ OV session created: {sess_id}")
        CREATED["ov_session_id"] = sess_id

    CREATED["ov_files"] = created_files
    save_json("created_openviking.json", {"files": created_files})


# ── Main ──────────────────────────────────────────────────────────────────────

LOADERS = {
    "admin": load_admin,
    "cognee": load_cognee,
    "graphiti": load_graphiti,
    "memobase": load_memobase,
    "zep": load_zep,
    "sm": load_supermemory,
    "agent": load_agent_memory,
    "observe": load_observe,
    "ov": load_openviking,
}

LOAD_ORDER = ["admin", "cognee", "graphiti", "memobase", "zep", "sm", "agent", "observe", "ov"]


def main() -> None:
    parser = argparse.ArgumentParser(description="Load VNP Memory seed data via API")
    parser.add_argument(
        "--engine",
        choices=list(LOADERS.keys()) + ["all"],
        default="all",
        help="Which engine to load (default: all)",
    )
    args = parser.parse_args()

    print(f"\n{'━' * 60}")
    print(" VNP Memory — Seed Data Loader")
    print(f" Server: {cfg.base_url}")
    print(f" Engine: {args.engine}")
    print(f"{'━' * 60}")

    engines = LOAD_ORDER if args.engine == "all" else [args.engine]
    errors = []

    for engine in engines:
        try:
            LOADERS[engine]()
        except FileNotFoundError as exc:
            print(f"\n  ❌ {exc}")
            errors.append(engine)
        except Exception as exc:
            print(f"\n  ❌ Error in '{engine}': {exc}")
            errors.append(engine)

    # Save summary
    save_json("created_summary.json", CREATED)

    print(f"\n{'━' * 60}")
    if errors:
        print(f" ⚠  Completed with errors in: {', '.join(errors)}")
    else:
        print(" ✅ All engines loaded successfully!")
    print(f" Summary saved to: {cfg.data_dir / 'created_summary.json'}")
    print(f"{'━' * 60}\n")
    print("Next step: python 03_verify_data.py")


if __name__ == "__main__":
    main()
