// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kgs-platform/internal/biz"
	"kgs-platform/internal/conf"
	"kgs-platform/internal/data"
	"kgs-platform/internal/server"
	"kgs-platform/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	registryService := service.NewRegistryService()
	ontologyService := service.NewOntologyService()
	graphRepo := data.NewGraphRepo(dataData, logger)
	queryPlanner := biz.NewQueryPlanner()
	opaClient := biz.NewOPAClient(logger)
	client := data.NewRedisClient(dataData)
	graphUsecase := biz.NewGraphUsecase(graphRepo, queryPlanner, opaClient, client, logger)
	graphService := service.NewGraphService(graphUsecase)
	rulesRepo := data.NewRulesRepo(dataData, logger)
	rulesUsecase := biz.NewRulesUsecase(rulesRepo, logger)
	rulesService := service.NewRulesService(rulesUsecase)
	policyRepo := data.NewPolicyRepo(dataData, logger)
	policyUsecase := biz.NewPolicyUsecase(policyRepo, logger)
	policyService := service.NewPolicyService(policyUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, registryService, ontologyService, graphService, rulesService, policyService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, registryService, ontologyService, graphService, rulesService, policyService, logger)
	ruleRunner := biz.NewRuleRunner(rulesRepo, graphRepo, logger)
	eventRunner := biz.NewEventRunner(rulesRepo, graphRepo, client, logger)
	policySyncRunner := biz.NewPolicySyncRunner(policyRepo, opaClient, logger)
	workerServer := server.NewWorkerServer(ruleRunner, eventRunner, policySyncRunner, logger)
	app := newApp(logger, grpcServer, httpServer, workerServer)
	return app, func() {
		cleanup()
	}, nil
}
