// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/analytics"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/batch"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/biz"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/conf"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/data"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/lock"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/overlay"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/projection"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/search"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/server"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/service"
	"github.com/blcvn/knowledge-gateway/kgs-platform/internal/version"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	registryRepo := data.NewRegistryRepo(dataData, logger)
	registryUsecase := biz.NewRegistryUsecase(registryRepo, logger)
	registryService := service.NewRegistryService(registryUsecase)
	graphRepo := data.NewGraphRepo(dataData, logger)
	ontologyRepo := data.NewOntologyRepo(dataData, logger)
	queryPlanner := biz.NewQueryPlanner()
	opaClient := biz.NewOPAClient(logger)
	ontologyValidatorConfig := newOntologyValidatorConfig(confData)
	ontologyValidator := biz.NewOntologyValidator(ontologyRepo, graphRepo, ontologyValidatorConfig, logger)
	client := data.NewRedisClient(dataData)
	redisLockManager := lock.NewRedisLockManager(client)
	contextDriver := data.NewNeo4jDriver(dataData)
	qdrantClient := data.NewQdrantClient(dataData)
	natsClient := data.NewNATSClient(dataData)
	db := data.NewGormDB(dataData)
	ontologyService := service.NewOntologyService(db, ontologyRepo)
	cache := analytics.NewCache(client)
	engine1 := analytics.NewEngine(graphRepo, cache)
	embeddingClient, err := search.NewEmbeddingClient(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	neo4jWriter := batch.NewNeo4jWriter(contextDriver)
	semanticDeduper := batch.NewSemanticDeduper(qdrantClient, embeddingClient)
	qdrantIndexer := batch.NewQdrantIndexer(qdrantClient, embeddingClient)
	usecase := batch.NewUsecaseWithIndexer(neo4jWriter, semanticDeduper, qdrantIndexer)
	vectorSearcher := search.NewVectorSearcher(qdrantClient, embeddingClient)
	textSearcher := search.NewTextSearcher(contextDriver, logger)
	neo4jCentralityProvider := search.NewNeo4jCentralityProvider(contextDriver)
	engine := search.NewEngine(vectorSearcher, textSearcher, neo4jCentralityProvider)
	versionManager := version.NewManager(db, logger)
	redisStore := overlay.NewRedisStore(client)
	overlayManager := overlay.NewManager(redisStore, versionManager, natsClient, logger)
	engine2 := projection.NewEngine(db, logger)
	graphUsecase := biz.NewGraphUsecase(graphRepo, queryPlanner, opaClient, ontologyValidator, client, redisLockManager, overlayManager, logger)
	graphService := service.NewGraphService(graphUsecase, usecase, engine, overlayManager, versionManager, engine1, engine2)
	rulesRepo := data.NewRulesRepo(dataData, logger)
	rulesUsecase := biz.NewRulesUsecase(rulesRepo, logger)
	rulesService := service.NewRulesService(rulesUsecase)
	policyRepo := data.NewPolicyRepo(dataData, logger)
	policyUsecase := biz.NewPolicyUsecase(policyRepo, logger)
	policyService := service.NewPolicyService(policyUsecase)
	healthService := service.NewHealthService(db, client, contextDriver, qdrantClient, natsClient, logger)
	viewResolver := biz.NewViewResolver(engine2)
	_ = viewResolver
	grpcServer := server.NewGRPCServer(confServer, greeterService, registryService, ontologyService, graphService, rulesService, policyService, registryUsecase, client, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, registryService, ontologyService, graphService, rulesService, policyService, healthService, registryUsecase, client, logger)
	ruleRunner := biz.NewRuleRunner(rulesRepo, graphRepo, logger)
	eventRunner := biz.NewEventRunner(rulesRepo, graphRepo, client, logger)
	policySyncRunner := biz.NewPolicySyncRunner(policyRepo, opaClient, logger)
	sessionCloseListener := overlay.NewSessionCloseListener(natsClient, overlayManager, logger)
	workerServer := server.NewWorkerServer(ruleRunner, eventRunner, policySyncRunner, sessionCloseListener, logger)
	app := newApp(logger, grpcServer, httpServer, workerServer)
	return app, func() {
		cleanup()
	}, nil
}
