// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: api/proto/memory/v1/agentmemory.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RememberAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // pattern|preference|architecture|bug|workflow|fact
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Concepts      []string               `protobuf:"bytes,4,rep,name=concepts,proto3" json:"concepts,omitempty"`
	Files         []string               `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Strength      float64                `protobuf:"fixed64,7,opt,name=strength,proto3" json:"strength,omitempty"` // default 0.7
	TenantId      string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Project       string                 `protobuf:"bytes,9,opt,name=project,proto3" json:"project,omitempty"`
	AgentId       string                 `protobuf:"bytes,10,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ForgetAfter   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=forget_after,json=forgetAfter,proto3,oneof" json:"forget_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberAgentRequest) Reset() {
	*x = RememberAgentRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberAgentRequest) ProtoMessage() {}

func (x *RememberAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberAgentRequest.ProtoReflect.Descriptor instead.
func (*RememberAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{0}
}

func (x *RememberAgentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RememberAgentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RememberAgentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RememberAgentRequest) GetConcepts() []string {
	if x != nil {
		return x.Concepts
	}
	return nil
}

func (x *RememberAgentRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *RememberAgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RememberAgentRequest) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *RememberAgentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RememberAgentRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RememberAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RememberAgentRequest) GetForgetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ForgetAfter
	}
	return nil
}

type RememberAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Superseded    []string               `protobuf:"bytes,3,rep,name=superseded,proto3" json:"superseded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberAgentResponse) Reset() {
	*x = RememberAgentResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberAgentResponse) ProtoMessage() {}

func (x *RememberAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberAgentResponse.ProtoReflect.Descriptor instead.
func (*RememberAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{1}
}

func (x *RememberAgentResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *RememberAgentResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RememberAgentResponse) GetSuperseded() []string {
	if x != nil {
		return x.Superseded
	}
	return nil
}

type AgentMemoryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Concepts      []string               `protobuf:"bytes,5,rep,name=concepts,proto3" json:"concepts,omitempty"`
	Files         []string               `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	Strength      float64                `protobuf:"fixed64,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	IsLatest      bool                   `protobuf:"varint,9,opt,name=is_latest,json=isLatest,proto3" json:"is_latest,omitempty"`
	AgentId       string                 `protobuf:"bytes,10,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Project       string                 `protobuf:"bytes,11,opt,name=project,proto3" json:"project,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMemoryProto) Reset() {
	*x = AgentMemoryProto{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMemoryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMemoryProto) ProtoMessage() {}

func (x *AgentMemoryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMemoryProto.ProtoReflect.Descriptor instead.
func (*AgentMemoryProto) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMemoryProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentMemoryProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentMemoryProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentMemoryProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentMemoryProto) GetConcepts() []string {
	if x != nil {
		return x.Concepts
	}
	return nil
}

func (x *AgentMemoryProto) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AgentMemoryProto) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *AgentMemoryProto) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AgentMemoryProto) GetIsLatest() bool {
	if x != nil {
		return x.IsLatest
	}
	return false
}

func (x *AgentMemoryProto) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMemoryProto) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AgentMemoryProto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentMemoryProto) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAgentMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	LatestOnly    bool                   `protobuf:"varint,4,opt,name=latest_only,json=latestOnly,proto3" json:"latest_only,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentMemoriesRequest) Reset() {
	*x = ListAgentMemoriesRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentMemoriesRequest) ProtoMessage() {}

func (x *ListAgentMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ListAgentMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentMemoriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAgentMemoriesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListAgentMemoriesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListAgentMemoriesRequest) GetLatestOnly() bool {
	if x != nil {
		return x.LatestOnly
	}
	return false
}

func (x *ListAgentMemoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentMemoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAgentMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*AgentMemoryProto    `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentMemoriesResponse) Reset() {
	*x = ListAgentMemoriesResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentMemoriesResponse) ProtoMessage() {}

func (x *ListAgentMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentMemoriesResponse.ProtoReflect.Descriptor instead.
func (*ListAgentMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentMemoriesResponse) GetMemories() []*AgentMemoryProto {
	if x != nil {
		return x.Memories
	}
	return nil
}

type GetAgentMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentMemoryRequest) Reset() {
	*x = GetAgentMemoryRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMemoryRequest) ProtoMessage() {}

func (x *GetAgentMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetAgentMemoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type GetAgentMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *AgentMemoryProto      `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentMemoryResponse) Reset() {
	*x = GetAgentMemoryResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMemoryResponse) ProtoMessage() {}

func (x *GetAgentMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetAgentMemoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentMemoryResponse) GetMemory() *AgentMemoryProto {
	if x != nil {
		return x.Memory
	}
	return nil
}

type DeleteAgentMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentMemoryRequest) Reset() {
	*x = DeleteAgentMemoryRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentMemoryRequest) ProtoMessage() {}

func (x *DeleteAgentMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentMemoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAgentMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *DeleteAgentMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteAgentMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentMemoryResponse) Reset() {
	*x = DeleteAgentMemoryResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentMemoryResponse) ProtoMessage() {}

func (x *DeleteAgentMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentMemoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAgentMemoryResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetRetentionScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRetentionScoreRequest) Reset() {
	*x = GetRetentionScoreRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetentionScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetentionScoreRequest) ProtoMessage() {}

func (x *GetRetentionScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetentionScoreRequest.ProtoReflect.Descriptor instead.
func (*GetRetentionScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{9}
}

func (x *GetRetentionScoreRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type GetRetentionScoreResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Score            float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	RecencyFactor    float64                `protobuf:"fixed64,2,opt,name=recency_factor,json=recencyFactor,proto3" json:"recency_factor,omitempty"`
	FrequencyFactor  float64                `protobuf:"fixed64,3,opt,name=frequency_factor,json=frequencyFactor,proto3" json:"frequency_factor,omitempty"`
	ImportanceFactor float64                `protobuf:"fixed64,4,opt,name=importance_factor,json=importanceFactor,proto3" json:"importance_factor,omitempty"`
	DaysSinceAccess  float64                `protobuf:"fixed64,5,opt,name=days_since_access,json=daysSinceAccess,proto3" json:"days_since_access,omitempty"`
	RecommendAction  string                 `protobuf:"bytes,6,opt,name=recommend_action,json=recommendAction,proto3" json:"recommend_action,omitempty"` // keep|review|evict
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRetentionScoreResponse) Reset() {
	*x = GetRetentionScoreResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetentionScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetentionScoreResponse) ProtoMessage() {}

func (x *GetRetentionScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetentionScoreResponse.ProtoReflect.Descriptor instead.
func (*GetRetentionScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{10}
}

func (x *GetRetentionScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GetRetentionScoreResponse) GetRecencyFactor() float64 {
	if x != nil {
		return x.RecencyFactor
	}
	return 0
}

func (x *GetRetentionScoreResponse) GetFrequencyFactor() float64 {
	if x != nil {
		return x.FrequencyFactor
	}
	return 0
}

func (x *GetRetentionScoreResponse) GetImportanceFactor() float64 {
	if x != nil {
		return x.ImportanceFactor
	}
	return 0
}

func (x *GetRetentionScoreResponse) GetDaysSinceAccess() float64 {
	if x != nil {
		return x.DaysSinceAccess
	}
	return 0
}

func (x *GetRetentionScoreResponse) GetRecommendAction() string {
	if x != nil {
		return x.RecommendAction
	}
	return ""
}

type EvictMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	MaxMemories   int32                  `protobuf:"varint,3,opt,name=max_memories,json=maxMemories,proto3" json:"max_memories,omitempty"`
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictMemoriesRequest) Reset() {
	*x = EvictMemoriesRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictMemoriesRequest) ProtoMessage() {}

func (x *EvictMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictMemoriesRequest.ProtoReflect.Descriptor instead.
func (*EvictMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{11}
}

func (x *EvictMemoriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EvictMemoriesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *EvictMemoriesRequest) GetMaxMemories() int32 {
	if x != nil {
		return x.MaxMemories
	}
	return 0
}

func (x *EvictMemoriesRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type EvictMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvictedIds    []string               `protobuf:"bytes,1,rep,name=evicted_ids,json=evictedIds,proto3" json:"evicted_ids,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictMemoriesResponse) Reset() {
	*x = EvictMemoriesResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictMemoriesResponse) ProtoMessage() {}

func (x *EvictMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictMemoriesResponse.ProtoReflect.Descriptor instead.
func (*EvictMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{12}
}

func (x *EvictMemoriesResponse) GetEvictedIds() []string {
	if x != nil {
		return x.EvictedIds
	}
	return nil
}

func (x *EvictMemoriesResponse) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type AutoForgetSweepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoForgetSweepRequest) Reset() {
	*x = AutoForgetSweepRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoForgetSweepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoForgetSweepRequest) ProtoMessage() {}

func (x *AutoForgetSweepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoForgetSweepRequest.ProtoReflect.Descriptor instead.
func (*AutoForgetSweepRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{13}
}

func (x *AutoForgetSweepRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type AutoForgetSweepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoForgetSweepResponse) Reset() {
	*x = AutoForgetSweepResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoForgetSweepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoForgetSweepResponse) ProtoMessage() {}

func (x *AutoForgetSweepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoForgetSweepResponse.ProtoReflect.Descriptor instead.
func (*AutoForgetSweepResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{14}
}

func (x *AutoForgetSweepResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type GetSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotRequest) Reset() {
	*x = GetSlotRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotRequest) ProtoMessage() {}

func (x *GetSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotRequest.ProtoReflect.Descriptor instead.
func (*GetSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{15}
}

func (x *GetSlotRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSlotRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetSlotRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotResponse) Reset() {
	*x = GetSlotResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotResponse) ProtoMessage() {}

func (x *GetSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotResponse.ProtoReflect.Descriptor instead.
func (*GetSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{16}
}

func (x *GetSlotResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetSlotResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type WriteSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"` // replace|append
	Project       string                 `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSlotRequest) Reset() {
	*x = WriteSlotRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSlotRequest) ProtoMessage() {}

func (x *WriteSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSlotRequest.ProtoReflect.Descriptor instead.
func (*WriteSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{17}
}

func (x *WriteSlotRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WriteSlotRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *WriteSlotRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *WriteSlotRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WriteSlotRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *WriteSlotRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type WriteSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSlotResponse) Reset() {
	*x = WriteSlotResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSlotResponse) ProtoMessage() {}

func (x *WriteSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSlotResponse.ProtoReflect.Descriptor instead.
func (*WriteSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{18}
}

func (x *WriteSlotResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSlotRequest) Reset() {
	*x = DeleteSlotRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSlotRequest) ProtoMessage() {}

func (x *DeleteSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSlotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteSlotRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteSlotRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DeleteSlotRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DeleteSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSlotResponse) Reset() {
	*x = DeleteSlotResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSlotResponse) ProtoMessage() {}

func (x *DeleteSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSlotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteSlotResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Pinned        bool                   `protobuf:"varint,4,opt,name=pinned,proto3" json:"pinned,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	SizeLimit     int32                  `protobuf:"varint,6,opt,name=size_limit,json=sizeLimit,proto3" json:"size_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotInfo) Reset() {
	*x = SlotInfo{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotInfo) ProtoMessage() {}

func (x *SlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotInfo.ProtoReflect.Descriptor instead.
func (*SlotInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{21}
}

func (x *SlotInfo) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SlotInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SlotInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SlotInfo) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *SlotInfo) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *SlotInfo) GetSizeLimit() int32 {
	if x != nil {
		return x.SizeLimit
	}
	return 0
}

type ListSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlotsRequest) Reset() {
	*x = ListSlotsRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlotsRequest) ProtoMessage() {}

func (x *ListSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlotsRequest.ProtoReflect.Descriptor instead.
func (*ListSlotsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{22}
}

func (x *ListSlotsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListSlotsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ListSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*SlotInfo            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlotsResponse) Reset() {
	*x = ListSlotsResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlotsResponse) ProtoMessage() {}

func (x *ListSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlotsResponse.ProtoReflect.Descriptor instead.
func (*ListSlotsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{23}
}

func (x *ListSlotsResponse) GetSlots() []*SlotInfo {
	if x != nil {
		return x.Slots
	}
	return nil
}

type SummarizeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeSessionRequest) Reset() {
	*x = SummarizeSessionRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeSessionRequest) ProtoMessage() {}

func (x *SummarizeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeSessionRequest.ProtoReflect.Descriptor instead.
func (*SummarizeSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{24}
}

func (x *SummarizeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SummarizeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeSessionResponse) Reset() {
	*x = SummarizeSessionResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeSessionResponse) ProtoMessage() {}

func (x *SummarizeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeSessionResponse.ProtoReflect.Descriptor instead.
func (*SummarizeSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{25}
}

func (x *SummarizeSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RunPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{26}
}

func (x *RunPipelineRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RunPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineResponse) Reset() {
	*x = RunPipelineResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineResponse) ProtoMessage() {}

func (x *RunPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineResponse.ProtoReflect.Descriptor instead.
func (*RunPipelineResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{27}
}

func (x *RunPipelineResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListProceduralRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProceduralRequest) Reset() {
	*x = ListProceduralRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProceduralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProceduralRequest) ProtoMessage() {}

func (x *ListProceduralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProceduralRequest.ProtoReflect.Descriptor instead.
func (*ListProceduralRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{28}
}

func (x *ListProceduralRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListProceduralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProceduralProto     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProceduralResponse) Reset() {
	*x = ListProceduralResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProceduralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProceduralResponse) ProtoMessage() {}

func (x *ListProceduralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProceduralResponse.ProtoReflect.Descriptor instead.
func (*ListProceduralResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{29}
}

func (x *ListProceduralResponse) GetItems() []*ProceduralProto {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProceduralProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Steps            []string               `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	TriggerCondition string                 `protobuf:"bytes,4,opt,name=trigger_condition,json=triggerCondition,proto3" json:"trigger_condition,omitempty"`
	ExpectedOutcome  string                 `protobuf:"bytes,5,opt,name=expected_outcome,json=expectedOutcome,proto3" json:"expected_outcome,omitempty"`
	Frequency        int32                  `protobuf:"varint,6,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProceduralProto) Reset() {
	*x = ProceduralProto{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProceduralProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProceduralProto) ProtoMessage() {}

func (x *ProceduralProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProceduralProto.ProtoReflect.Descriptor instead.
func (*ProceduralProto) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{30}
}

func (x *ProceduralProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProceduralProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProceduralProto) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ProceduralProto) GetTriggerCondition() string {
	if x != nil {
		return x.TriggerCondition
	}
	return ""
}

func (x *ProceduralProto) GetExpectedOutcome() string {
	if x != nil {
		return x.ExpectedOutcome
	}
	return ""
}

func (x *ProceduralProto) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type ListLessonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLessonsRequest) Reset() {
	*x = ListLessonsRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLessonsRequest) ProtoMessage() {}

func (x *ListLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLessonsRequest.ProtoReflect.Descriptor instead.
func (*ListLessonsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{31}
}

func (x *ListLessonsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListLessonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LessonProto         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLessonsResponse) Reset() {
	*x = ListLessonsResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLessonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLessonsResponse) ProtoMessage() {}

func (x *ListLessonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLessonsResponse.ProtoReflect.Descriptor instead.
func (*ListLessonsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{32}
}

func (x *ListLessonsResponse) GetItems() []*LessonProto {
	if x != nil {
		return x.Items
	}
	return nil
}

type LessonProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Categories    []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonProto) Reset() {
	*x = LessonProto{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonProto) ProtoMessage() {}

func (x *LessonProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonProto.ProtoReflect.Descriptor instead.
func (*LessonProto) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{33}
}

func (x *LessonProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LessonProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LessonProto) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *LessonProto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListInsightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInsightsRequest) Reset() {
	*x = ListInsightsRequest{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInsightsRequest) ProtoMessage() {}

func (x *ListInsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInsightsRequest.ProtoReflect.Descriptor instead.
func (*ListInsightsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{34}
}

func (x *ListInsightsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListInsightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InsightProto        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInsightsResponse) Reset() {
	*x = ListInsightsResponse{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInsightsResponse) ProtoMessage() {}

func (x *ListInsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInsightsResponse.ProtoReflect.Descriptor instead.
func (*ListInsightsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{35}
}

func (x *ListInsightsResponse) GetItems() []*InsightProto {
	if x != nil {
		return x.Items
	}
	return nil
}

type InsightProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LessonIds     []string               `protobuf:"bytes,3,rep,name=lesson_ids,json=lessonIds,proto3" json:"lesson_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightProto) Reset() {
	*x = InsightProto{}
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightProto) ProtoMessage() {}

func (x *InsightProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memory_v1_agentmemory_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightProto.ProtoReflect.Descriptor instead.
func (*InsightProto) Descriptor() ([]byte, []int) {
	return file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP(), []int{36}
}

func (x *InsightProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsightProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InsightProto) GetLessonIds() []string {
	if x != nil {
		return x.LessonIds
	}
	return nil
}

var File_api_proto_memory_v1_agentmemory_proto protoreflect.FileDescriptor

const file_api_proto_memory_v1_agentmemory_proto_rawDesc = "" +
	"\n" +
	"%api/proto/memory/v1/agentmemory.proto\x12\tmemory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x02\n" +
	"\x14RememberAgentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bconcepts\x18\x04 \x03(\tR\bconcepts\x12\x14\n" +
	"\x05files\x18\x05 \x03(\tR\x05files\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bstrength\x18\a \x01(\x01R\bstrength\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12\x18\n" +
	"\aproject\x18\t \x01(\tR\aproject\x12\x19\n" +
	"\bagent_id\x18\n" +
	" \x01(\tR\aagentId\x12B\n" +
	"\fforget_after\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vforgetAfter\x88\x01\x01B\x0f\n" +
	"\r_forget_after\"n\n" +
	"\x15RememberAgentResponse\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1e\n" +
	"\n" +
	"superseded\x18\x03 \x03(\tR\n" +
	"superseded\"\x96\x03\n" +
	"\x10AgentMemoryProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bconcepts\x18\x05 \x03(\tR\bconcepts\x12\x14\n" +
	"\x05files\x18\x06 \x03(\tR\x05files\x12\x1a\n" +
	"\bstrength\x18\a \x01(\x01R\bstrength\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x12\x1b\n" +
	"\tis_latest\x18\t \x01(\bR\bisLatest\x12\x19\n" +
	"\bagent_id\x18\n" +
	" \x01(\tR\aagentId\x12\x18\n" +
	"\aproject\x18\v \x01(\tR\aproject\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb4\x01\n" +
	"\x18ListAgentMemoriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vlatest_only\x18\x04 \x01(\bR\n" +
	"latestOnly\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"T\n" +
	"\x19ListAgentMemoriesResponse\x127\n" +
	"\bmemories\x18\x01 \x03(\v2\x1b.memory.v1.AgentMemoryProtoR\bmemories\"4\n" +
	"\x15GetAgentMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\"M\n" +
	"\x16GetAgentMemoryResponse\x123\n" +
	"\x06memory\x18\x01 \x01(\v2\x1b.memory.v1.AgentMemoryProtoR\x06memory\"T\n" +
	"\x18DeleteAgentMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"5\n" +
	"\x19DeleteAgentMemoryResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"7\n" +
	"\x18GetRetentionScoreRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\"\x87\x02\n" +
	"\x19GetRetentionScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12%\n" +
	"\x0erecency_factor\x18\x02 \x01(\x01R\rrecencyFactor\x12)\n" +
	"\x10frequency_factor\x18\x03 \x01(\x01R\x0ffrequencyFactor\x12+\n" +
	"\x11importance_factor\x18\x04 \x01(\x01R\x10importanceFactor\x12*\n" +
	"\x11days_since_access\x18\x05 \x01(\x01R\x0fdaysSinceAccess\x12)\n" +
	"\x10recommend_action\x18\x06 \x01(\tR\x0frecommendAction\"\x89\x01\n" +
	"\x14EvictMemoriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12!\n" +
	"\fmax_memories\x18\x03 \x01(\x05R\vmaxMemories\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"Q\n" +
	"\x15EvictMemoriesResponse\x12\x1f\n" +
	"\vevicted_ids\x18\x01 \x03(\tR\n" +
	"evictedIds\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"5\n" +
	"\x16AutoForgetSweepRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\">\n" +
	"\x17AutoForgetSweepResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"Y\n" +
	"\x0eGetSlotRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"C\n" +
	"\x0fGetSlotResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"\xa3\x01\n" +
	"\x10WriteSlotRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x18\n" +
	"\aproject\x18\x06 \x01(\tR\aproject\"#\n" +
	"\x11WriteSlotResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\\\n" +
	"\x11DeleteSlotRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\".\n" +
	"\x12DeleteSlotResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xac\x01\n" +
	"\bSlotInfo\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06pinned\x18\x04 \x01(\bR\x06pinned\x12\x1b\n" +
	"\tread_only\x18\x05 \x01(\bR\breadOnly\x12\x1d\n" +
	"\n" +
	"size_limit\x18\x06 \x01(\x05R\tsizeLimit\"E\n" +
	"\x10ListSlotsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\">\n" +
	"\x11ListSlotsResponse\x12)\n" +
	"\x05slots\x18\x01 \x03(\v2\x13.memory.v1.SlotInfoR\x05slots\"8\n" +
	"\x17SummarizeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"*\n" +
	"\x18SummarizeSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"3\n" +
	"\x12RunPipelineRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"%\n" +
	"\x13RunPipelineResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"4\n" +
	"\x15ListProceduralRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"J\n" +
	"\x16ListProceduralResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.memory.v1.ProceduralProtoR\x05items\"\xc1\x01\n" +
	"\x0fProceduralProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05steps\x18\x03 \x03(\tR\x05steps\x12+\n" +
	"\x11trigger_condition\x18\x04 \x01(\tR\x10triggerCondition\x12)\n" +
	"\x10expected_outcome\x18\x05 \x01(\tR\x0fexpectedOutcome\x12\x1c\n" +
	"\tfrequency\x18\x06 \x01(\x05R\tfrequency\"1\n" +
	"\x12ListLessonsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"C\n" +
	"\x13ListLessonsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.memory.v1.LessonProtoR\x05items\"o\n" +
	"\vLessonProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"2\n" +
	"\x13ListInsightsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"E\n" +
	"\x14ListInsightsResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.memory.v1.InsightProtoR\x05items\"W\n" +
	"\fInsightProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"lesson_ids\x18\x03 \x03(\tR\tlessonIds2\xaa\a\n" +
	"\x12AgentMemoryService\x12R\n" +
	"\rRememberAgent\x12\x1f.memory.v1.RememberAgentRequest\x1a .memory.v1.RememberAgentResponse\x12^\n" +
	"\x11ListAgentMemories\x12#.memory.v1.ListAgentMemoriesRequest\x1a$.memory.v1.ListAgentMemoriesResponse\x12U\n" +
	"\x0eGetAgentMemory\x12 .memory.v1.GetAgentMemoryRequest\x1a!.memory.v1.GetAgentMemoryResponse\x12^\n" +
	"\x11DeleteAgentMemory\x12#.memory.v1.DeleteAgentMemoryRequest\x1a$.memory.v1.DeleteAgentMemoryResponse\x12^\n" +
	"\x11GetRetentionScore\x12#.memory.v1.GetRetentionScoreRequest\x1a$.memory.v1.GetRetentionScoreResponse\x12R\n" +
	"\rEvictMemories\x12\x1f.memory.v1.EvictMemoriesRequest\x1a .memory.v1.EvictMemoriesResponse\x12X\n" +
	"\x0fAutoForgetSweep\x12!.memory.v1.AutoForgetSweepRequest\x1a\".memory.v1.AutoForgetSweepResponse\x12@\n" +
	"\aGetSlot\x12\x19.memory.v1.GetSlotRequest\x1a\x1a.memory.v1.GetSlotResponse\x12F\n" +
	"\tWriteSlot\x12\x1b.memory.v1.WriteSlotRequest\x1a\x1c.memory.v1.WriteSlotResponse\x12I\n" +
	"\n" +
	"DeleteSlot\x12\x1c.memory.v1.DeleteSlotRequest\x1a\x1d.memory.v1.DeleteSlotResponse\x12F\n" +
	"\tListSlots\x12\x1b.memory.v1.ListSlotsRequest\x1a\x1c.memory.v1.ListSlotsResponse2\xb7\x03\n" +
	"\x14ConsolidationService\x12[\n" +
	"\x10SummarizeSession\x12\".memory.v1.SummarizeSessionRequest\x1a#.memory.v1.SummarizeSessionResponse\x12L\n" +
	"\vRunPipeline\x12\x1d.memory.v1.RunPipelineRequest\x1a\x1e.memory.v1.RunPipelineResponse\x12U\n" +
	"\x0eListProcedural\x12 .memory.v1.ListProceduralRequest\x1a!.memory.v1.ListProceduralResponse\x12L\n" +
	"\vListLessons\x12\x1d.memory.v1.ListLessonsRequest\x1a\x1e.memory.v1.ListLessonsResponse\x12O\n" +
	"\fListInsights\x12\x1e.memory.v1.ListInsightsRequest\x1a\x1f.memory.v1.ListInsightsResponseB+Z)github.com/vnp-memory/api/proto/memory/v1b\x06proto3"

var (
	file_api_proto_memory_v1_agentmemory_proto_rawDescOnce sync.Once
	file_api_proto_memory_v1_agentmemory_proto_rawDescData []byte
)

func file_api_proto_memory_v1_agentmemory_proto_rawDescGZIP() []byte {
	file_api_proto_memory_v1_agentmemory_proto_rawDescOnce.Do(func() {
		file_api_proto_memory_v1_agentmemory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_memory_v1_agentmemory_proto_rawDesc), len(file_api_proto_memory_v1_agentmemory_proto_rawDesc)))
	})
	return file_api_proto_memory_v1_agentmemory_proto_rawDescData
}

var file_api_proto_memory_v1_agentmemory_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_api_proto_memory_v1_agentmemory_proto_goTypes = []any{
	(*RememberAgentRequest)(nil),      // 0: memory.v1.RememberAgentRequest
	(*RememberAgentResponse)(nil),     // 1: memory.v1.RememberAgentResponse
	(*AgentMemoryProto)(nil),          // 2: memory.v1.AgentMemoryProto
	(*ListAgentMemoriesRequest)(nil),  // 3: memory.v1.ListAgentMemoriesRequest
	(*ListAgentMemoriesResponse)(nil), // 4: memory.v1.ListAgentMemoriesResponse
	(*GetAgentMemoryRequest)(nil),     // 5: memory.v1.GetAgentMemoryRequest
	(*GetAgentMemoryResponse)(nil),    // 6: memory.v1.GetAgentMemoryResponse
	(*DeleteAgentMemoryRequest)(nil),  // 7: memory.v1.DeleteAgentMemoryRequest
	(*DeleteAgentMemoryResponse)(nil), // 8: memory.v1.DeleteAgentMemoryResponse
	(*GetRetentionScoreRequest)(nil),  // 9: memory.v1.GetRetentionScoreRequest
	(*GetRetentionScoreResponse)(nil), // 10: memory.v1.GetRetentionScoreResponse
	(*EvictMemoriesRequest)(nil),      // 11: memory.v1.EvictMemoriesRequest
	(*EvictMemoriesResponse)(nil),     // 12: memory.v1.EvictMemoriesResponse
	(*AutoForgetSweepRequest)(nil),    // 13: memory.v1.AutoForgetSweepRequest
	(*AutoForgetSweepResponse)(nil),   // 14: memory.v1.AutoForgetSweepResponse
	(*GetSlotRequest)(nil),            // 15: memory.v1.GetSlotRequest
	(*GetSlotResponse)(nil),           // 16: memory.v1.GetSlotResponse
	(*WriteSlotRequest)(nil),          // 17: memory.v1.WriteSlotRequest
	(*WriteSlotResponse)(nil),         // 18: memory.v1.WriteSlotResponse
	(*DeleteSlotRequest)(nil),         // 19: memory.v1.DeleteSlotRequest
	(*DeleteSlotResponse)(nil),        // 20: memory.v1.DeleteSlotResponse
	(*SlotInfo)(nil),                  // 21: memory.v1.SlotInfo
	(*ListSlotsRequest)(nil),          // 22: memory.v1.ListSlotsRequest
	(*ListSlotsResponse)(nil),         // 23: memory.v1.ListSlotsResponse
	(*SummarizeSessionRequest)(nil),   // 24: memory.v1.SummarizeSessionRequest
	(*SummarizeSessionResponse)(nil),  // 25: memory.v1.SummarizeSessionResponse
	(*RunPipelineRequest)(nil),        // 26: memory.v1.RunPipelineRequest
	(*RunPipelineResponse)(nil),       // 27: memory.v1.RunPipelineResponse
	(*ListProceduralRequest)(nil),     // 28: memory.v1.ListProceduralRequest
	(*ListProceduralResponse)(nil),    // 29: memory.v1.ListProceduralResponse
	(*ProceduralProto)(nil),           // 30: memory.v1.ProceduralProto
	(*ListLessonsRequest)(nil),        // 31: memory.v1.ListLessonsRequest
	(*ListLessonsResponse)(nil),       // 32: memory.v1.ListLessonsResponse
	(*LessonProto)(nil),               // 33: memory.v1.LessonProto
	(*ListInsightsRequest)(nil),       // 34: memory.v1.ListInsightsRequest
	(*ListInsightsResponse)(nil),      // 35: memory.v1.ListInsightsResponse
	(*InsightProto)(nil),              // 36: memory.v1.InsightProto
	(*timestamppb.Timestamp)(nil),     // 37: google.protobuf.Timestamp
}
var file_api_proto_memory_v1_agentmemory_proto_depIdxs = []int32{
	37, // 0: memory.v1.RememberAgentRequest.forget_after:type_name -> google.protobuf.Timestamp
	37, // 1: memory.v1.AgentMemoryProto.created_at:type_name -> google.protobuf.Timestamp
	37, // 2: memory.v1.AgentMemoryProto.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: memory.v1.ListAgentMemoriesResponse.memories:type_name -> memory.v1.AgentMemoryProto
	2,  // 4: memory.v1.GetAgentMemoryResponse.memory:type_name -> memory.v1.AgentMemoryProto
	21, // 5: memory.v1.ListSlotsResponse.slots:type_name -> memory.v1.SlotInfo
	30, // 6: memory.v1.ListProceduralResponse.items:type_name -> memory.v1.ProceduralProto
	33, // 7: memory.v1.ListLessonsResponse.items:type_name -> memory.v1.LessonProto
	36, // 8: memory.v1.ListInsightsResponse.items:type_name -> memory.v1.InsightProto
	0,  // 9: memory.v1.AgentMemoryService.RememberAgent:input_type -> memory.v1.RememberAgentRequest
	3,  // 10: memory.v1.AgentMemoryService.ListAgentMemories:input_type -> memory.v1.ListAgentMemoriesRequest
	5,  // 11: memory.v1.AgentMemoryService.GetAgentMemory:input_type -> memory.v1.GetAgentMemoryRequest
	7,  // 12: memory.v1.AgentMemoryService.DeleteAgentMemory:input_type -> memory.v1.DeleteAgentMemoryRequest
	9,  // 13: memory.v1.AgentMemoryService.GetRetentionScore:input_type -> memory.v1.GetRetentionScoreRequest
	11, // 14: memory.v1.AgentMemoryService.EvictMemories:input_type -> memory.v1.EvictMemoriesRequest
	13, // 15: memory.v1.AgentMemoryService.AutoForgetSweep:input_type -> memory.v1.AutoForgetSweepRequest
	15, // 16: memory.v1.AgentMemoryService.GetSlot:input_type -> memory.v1.GetSlotRequest
	17, // 17: memory.v1.AgentMemoryService.WriteSlot:input_type -> memory.v1.WriteSlotRequest
	19, // 18: memory.v1.AgentMemoryService.DeleteSlot:input_type -> memory.v1.DeleteSlotRequest
	22, // 19: memory.v1.AgentMemoryService.ListSlots:input_type -> memory.v1.ListSlotsRequest
	24, // 20: memory.v1.ConsolidationService.SummarizeSession:input_type -> memory.v1.SummarizeSessionRequest
	26, // 21: memory.v1.ConsolidationService.RunPipeline:input_type -> memory.v1.RunPipelineRequest
	28, // 22: memory.v1.ConsolidationService.ListProcedural:input_type -> memory.v1.ListProceduralRequest
	31, // 23: memory.v1.ConsolidationService.ListLessons:input_type -> memory.v1.ListLessonsRequest
	34, // 24: memory.v1.ConsolidationService.ListInsights:input_type -> memory.v1.ListInsightsRequest
	1,  // 25: memory.v1.AgentMemoryService.RememberAgent:output_type -> memory.v1.RememberAgentResponse
	4,  // 26: memory.v1.AgentMemoryService.ListAgentMemories:output_type -> memory.v1.ListAgentMemoriesResponse
	6,  // 27: memory.v1.AgentMemoryService.GetAgentMemory:output_type -> memory.v1.GetAgentMemoryResponse
	8,  // 28: memory.v1.AgentMemoryService.DeleteAgentMemory:output_type -> memory.v1.DeleteAgentMemoryResponse
	10, // 29: memory.v1.AgentMemoryService.GetRetentionScore:output_type -> memory.v1.GetRetentionScoreResponse
	12, // 30: memory.v1.AgentMemoryService.EvictMemories:output_type -> memory.v1.EvictMemoriesResponse
	14, // 31: memory.v1.AgentMemoryService.AutoForgetSweep:output_type -> memory.v1.AutoForgetSweepResponse
	16, // 32: memory.v1.AgentMemoryService.GetSlot:output_type -> memory.v1.GetSlotResponse
	18, // 33: memory.v1.AgentMemoryService.WriteSlot:output_type -> memory.v1.WriteSlotResponse
	20, // 34: memory.v1.AgentMemoryService.DeleteSlot:output_type -> memory.v1.DeleteSlotResponse
	23, // 35: memory.v1.AgentMemoryService.ListSlots:output_type -> memory.v1.ListSlotsResponse
	25, // 36: memory.v1.ConsolidationService.SummarizeSession:output_type -> memory.v1.SummarizeSessionResponse
	27, // 37: memory.v1.ConsolidationService.RunPipeline:output_type -> memory.v1.RunPipelineResponse
	29, // 38: memory.v1.ConsolidationService.ListProcedural:output_type -> memory.v1.ListProceduralResponse
	32, // 39: memory.v1.ConsolidationService.ListLessons:output_type -> memory.v1.ListLessonsResponse
	35, // 40: memory.v1.ConsolidationService.ListInsights:output_type -> memory.v1.ListInsightsResponse
	25, // [25:41] is the sub-list for method output_type
	9,  // [9:25] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_memory_v1_agentmemory_proto_init() }
func file_api_proto_memory_v1_agentmemory_proto_init() {
	if File_api_proto_memory_v1_agentmemory_proto != nil {
		return
	}
	file_api_proto_memory_v1_agentmemory_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_memory_v1_agentmemory_proto_rawDesc), len(file_api_proto_memory_v1_agentmemory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_memory_v1_agentmemory_proto_goTypes,
		DependencyIndexes: file_api_proto_memory_v1_agentmemory_proto_depIdxs,
		MessageInfos:      file_api_proto_memory_v1_agentmemory_proto_msgTypes,
	}.Build()
	File_api_proto_memory_v1_agentmemory_proto = out.File
	file_api_proto_memory_v1_agentmemory_proto_goTypes = nil
	file_api_proto_memory_v1_agentmemory_proto_depIdxs = nil
}
