// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/cognee/ingestion/v1/ingestion.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	DatasetName   string                 `protobuf:"bytes,2,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Items         []*DataItem            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	NodeSets      []string               `protobuf:"bytes,5,rep,name=node_sets,json=nodeSets,proto3" json:"node_sets,omitempty"` // [NEW] CR-002
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataRequest) Reset() {
	*x = AddDataRequest{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataRequest) ProtoMessage() {}

func (x *AddDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataRequest.ProtoReflect.Descriptor instead.
func (*AddDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *AddDataRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *AddDataRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *AddDataRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AddDataRequest) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AddDataRequest) GetNodeSets() []string {
	if x != nil {
		return x.NodeSets
	}
	return nil
}

type DataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // TEXT | PDF | PDF_LAYOUT | HTML | URL | DOCX | CSV | TABULAR_FK
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        *DataItemConfig        `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"` // [NEW] CR-004
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *DataItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DataItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DataItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DataItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataItem) GetConfig() *DataItemConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DataItemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfMode       string                 `protobuf:"bytes,1,opt,name=pdf_mode,json=pdfMode,proto3" json:"pdf_mode,omitempty"` // "LAYOUT_AWARE" | "PLAIN_TEXT"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItemConfig) Reset() {
	*x = DataItemConfig{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItemConfig) ProtoMessage() {}

func (x *DataItemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItemConfig.ProtoReflect.Descriptor instead.
func (*DataItemConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *DataItemConfig) GetPdfMode() string {
	if x != nil {
		return x.PdfMode
	}
	return ""
}

type AddDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	EntryIds      []string               `protobuf:"bytes,2,rep,name=entry_ids,json=entryIds,proto3" json:"entry_ids,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataResponse) Reset() {
	*x = AddDataResponse{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataResponse) ProtoMessage() {}

func (x *AddDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataResponse.ProtoReflect.Descriptor instead.
func (*AddDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *AddDataResponse) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *AddDataResponse) GetEntryIds() []string {
	if x != nil {
		return x.EntryIds
	}
	return nil
}

func (x *AddDataResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddDataPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DataPoints    []*DataPoint           `protobuf:"bytes,3,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	NodeSets      []string               `protobuf:"bytes,4,rep,name=node_sets,json=nodeSets,proto3" json:"node_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataPointsRequest) Reset() {
	*x = AddDataPointsRequest{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataPointsRequest) ProtoMessage() {}

func (x *AddDataPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataPointsRequest.ProtoReflect.Descriptor instead.
func (*AddDataPointsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *AddDataPointsRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *AddDataPointsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AddDataPointsRequest) GetDataPoints() []*DataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *AddDataPointsRequest) GetNodeSets() []string {
	if x != nil {
		return x.NodeSets
	}
	return nil
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // stable deterministic UUID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                  // e.g. "Paper", "Employee", "Product"
	Fields        *structpb.Struct       `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`                              // all field values
	IndexFields   []string               `protobuf:"bytes,4,rep,name=index_fields,json=indexFields,proto3" json:"index_fields,omitempty"` // fields to embed into Qdrant
	Relations     []*Relation            `protobuf:"bytes,5,rep,name=relations,proto3" json:"relations,omitempty"`                        // explicit FK edges
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{5}
}

func (x *DataPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataPoint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataPoint) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataPoint) GetIndexFields() []string {
	if x != nil {
		return x.IndexFields
	}
	return nil
}

func (x *DataPoint) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`     // edge label: "authored_by", "works_in", ...
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"` // default: 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{6}
}

func (x *Relation) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Relation) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Relation) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type AddDataPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upserted      int32                  `protobuf:"varint,1,opt,name=upserted,proto3" json:"upserted,omitempty"`
	Created       int32                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated       int32                  `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataPointsResponse) Reset() {
	*x = AddDataPointsResponse{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataPointsResponse) ProtoMessage() {}

func (x *AddDataPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataPointsResponse.ProtoReflect.Descriptor instead.
func (*AddDataPointsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{7}
}

func (x *AddDataPointsResponse) GetUpserted() int32 {
	if x != nil {
		return x.Upserted
	}
	return 0
}

func (x *AddDataPointsResponse) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *AddDataPointsResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{8}
}

func (x *ListDatasetsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDatasetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDatasetsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DatasetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	DatasetName   string                 `protobuf:"bytes,2,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	EntryCount    int32                  `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetInfo) Reset() {
	*x = DatasetInfo{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetInfo) ProtoMessage() {}

func (x *DatasetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetInfo.ProtoReflect.Descriptor instead.
func (*DatasetInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{9}
}

func (x *DatasetInfo) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *DatasetInfo) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *DatasetInfo) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *DatasetInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*DatasetInfo         `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{10}
}

func (x *ListDatasetsResponse) GetDatasets() []*DatasetInfo {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type ListDataEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	DatasetName   string                 `protobuf:"bytes,3,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataEntriesRequest) Reset() {
	*x = ListDataEntriesRequest{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataEntriesRequest) ProtoMessage() {}

func (x *ListDataEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListDataEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{11}
}

func (x *ListDataEntriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDataEntriesRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *ListDataEntriesRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *ListDataEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDataEntriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DataEntryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,4,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntryInfo) Reset() {
	*x = DataEntryInfo{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntryInfo) ProtoMessage() {}

func (x *DataEntryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntryInfo.ProtoReflect.Descriptor instead.
func (*DataEntryInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{12}
}

func (x *DataEntryInfo) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *DataEntryInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DataEntryInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DataEntryInfo) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type ListDataEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DataEntryInfo       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataEntriesResponse) Reset() {
	*x = ListDataEntriesResponse{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataEntriesResponse) ProtoMessage() {}

func (x *ListDataEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListDataEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{13}
}

func (x *ListDataEntriesResponse) GetEntries() []*DataEntryInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DeleteDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	DatasetName   string                 `protobuf:"bytes,3,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatasetRequest) Reset() {
	*x = DeleteDatasetRequest{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetRequest) ProtoMessage() {}

func (x *DeleteDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatasetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDatasetRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteDatasetRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *DeleteDatasetRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

type DeleteDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatasetResponse) Reset() {
	*x = DeleteDatasetResponse{}
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetResponse) ProtoMessage() {}

func (x *DeleteDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatasetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDatasetResponse) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *DeleteDatasetResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_api_proto_cognee_ingestion_v1_ingestion_proto protoreflect.FileDescriptor

const file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDesc = "" +
	"\n" +
	"-api/proto/cognee/ingestion/v1/ingestion.proto\x12\x13cognee.ingestion.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xc1\x01\n" +
	"\x0eAddDataRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12!\n" +
	"\fdataset_name\x18\x02 \x01(\tR\vdatasetName\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x123\n" +
	"\x05items\x18\x04 \x03(\v2\x1d.cognee.ingestion.v1.DataItemR\x05items\x12\x1b\n" +
	"\tnode_sets\x18\x05 \x03(\tR\bnodeSets\"\x9c\x02\n" +
	"\bDataItem\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.cognee.ingestion.v1.DataItem.MetadataEntryR\bmetadata\x12;\n" +
	"\x06config\x18\x05 \x01(\v2#.cognee.ingestion.v1.DataItemConfigR\x06config\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x0eDataItemConfig\x12\x19\n" +
	"\bpdf_mode\x18\x01 \x01(\tR\apdfMode\"c\n" +
	"\x0fAddDataResponse\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12\x1b\n" +
	"\tentry_ids\x18\x02 \x03(\tR\bentryIds\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xb0\x01\n" +
	"\x14AddDataPointsRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12?\n" +
	"\vdata_points\x18\x03 \x03(\v2\x1e.cognee.ingestion.v1.DataPointR\n" +
	"dataPoints\x12\x1b\n" +
	"\tnode_sets\x18\x04 \x03(\tR\bnodeSets\"\xc0\x01\n" +
	"\tDataPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12/\n" +
	"\x06fields\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06fields\x12!\n" +
	"\findex_fields\x18\x04 \x03(\tR\vindexFields\x12;\n" +
	"\trelations\x18\x05 \x03(\v2\x1d.cognee.ingestion.v1.RelationR\trelations\"U\n" +
	"\bRelation\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\"g\n" +
	"\x15AddDataPointsResponse\x12\x1a\n" +
	"\bupserted\x18\x01 \x01(\x05R\bupserted\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\x05R\aupdated\"`\n" +
	"\x13ListDatasetsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8f\x01\n" +
	"\vDatasetInfo\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12!\n" +
	"\fdataset_name\x18\x02 \x01(\tR\vdatasetName\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x05R\n" +
	"entryCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"T\n" +
	"\x14ListDatasetsResponse\x12<\n" +
	"\bdatasets\x18\x01 \x03(\v2 .cognee.ingestion.v1.DatasetInfoR\bdatasets\"\xa5\x01\n" +
	"\x16ListDataEntriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12!\n" +
	"\fdataset_name\x18\x03 \x01(\tR\vdatasetName\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"\x8d\x01\n" +
	"\rDataEntryInfo\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vchunk_count\x18\x04 \x01(\x05R\n" +
	"chunkCount\"W\n" +
	"\x17ListDataEntriesResponse\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".cognee.ingestion.v1.DataEntryInfoR\aentries\"u\n" +
	"\x14DeleteDatasetRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12!\n" +
	"\fdataset_name\x18\x03 \x01(\tR\vdatasetName\"P\n" +
	"\x15DeleteDatasetResponse\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted2\x8b\x04\n" +
	"\x10IngestionService\x12T\n" +
	"\aAddData\x12#.cognee.ingestion.v1.AddDataRequest\x1a$.cognee.ingestion.v1.AddDataResponse\x12f\n" +
	"\rAddDataPoints\x12).cognee.ingestion.v1.AddDataPointsRequest\x1a*.cognee.ingestion.v1.AddDataPointsResponse\x12c\n" +
	"\fListDatasets\x12(.cognee.ingestion.v1.ListDatasetsRequest\x1a).cognee.ingestion.v1.ListDatasetsResponse\x12l\n" +
	"\x0fListDataEntries\x12+.cognee.ingestion.v1.ListDataEntriesRequest\x1a,.cognee.ingestion.v1.ListDataEntriesResponse\x12f\n" +
	"\rDeleteDataset\x12).cognee.ingestion.v1.DeleteDatasetRequest\x1a*.cognee.ingestion.v1.DeleteDatasetResponseB5Z3github.com/vnp-memory/api/proto/cognee/ingestion/v1b\x06proto3"

var (
	file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescOnce sync.Once
	file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescData []byte
)

func file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescGZIP() []byte {
	file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDesc), len(file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDesc)))
	})
	return file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDescData
}

var file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_cognee_ingestion_v1_ingestion_proto_goTypes = []any{
	(*AddDataRequest)(nil),          // 0: cognee.ingestion.v1.AddDataRequest
	(*DataItem)(nil),                // 1: cognee.ingestion.v1.DataItem
	(*DataItemConfig)(nil),          // 2: cognee.ingestion.v1.DataItemConfig
	(*AddDataResponse)(nil),         // 3: cognee.ingestion.v1.AddDataResponse
	(*AddDataPointsRequest)(nil),    // 4: cognee.ingestion.v1.AddDataPointsRequest
	(*DataPoint)(nil),               // 5: cognee.ingestion.v1.DataPoint
	(*Relation)(nil),                // 6: cognee.ingestion.v1.Relation
	(*AddDataPointsResponse)(nil),   // 7: cognee.ingestion.v1.AddDataPointsResponse
	(*ListDatasetsRequest)(nil),     // 8: cognee.ingestion.v1.ListDatasetsRequest
	(*DatasetInfo)(nil),             // 9: cognee.ingestion.v1.DatasetInfo
	(*ListDatasetsResponse)(nil),    // 10: cognee.ingestion.v1.ListDatasetsResponse
	(*ListDataEntriesRequest)(nil),  // 11: cognee.ingestion.v1.ListDataEntriesRequest
	(*DataEntryInfo)(nil),           // 12: cognee.ingestion.v1.DataEntryInfo
	(*ListDataEntriesResponse)(nil), // 13: cognee.ingestion.v1.ListDataEntriesResponse
	(*DeleteDatasetRequest)(nil),    // 14: cognee.ingestion.v1.DeleteDatasetRequest
	(*DeleteDatasetResponse)(nil),   // 15: cognee.ingestion.v1.DeleteDatasetResponse
	nil,                             // 16: cognee.ingestion.v1.DataItem.MetadataEntry
	(*structpb.Struct)(nil),         // 17: google.protobuf.Struct
}
var file_api_proto_cognee_ingestion_v1_ingestion_proto_depIdxs = []int32{
	1,  // 0: cognee.ingestion.v1.AddDataRequest.items:type_name -> cognee.ingestion.v1.DataItem
	16, // 1: cognee.ingestion.v1.DataItem.metadata:type_name -> cognee.ingestion.v1.DataItem.MetadataEntry
	2,  // 2: cognee.ingestion.v1.DataItem.config:type_name -> cognee.ingestion.v1.DataItemConfig
	5,  // 3: cognee.ingestion.v1.AddDataPointsRequest.data_points:type_name -> cognee.ingestion.v1.DataPoint
	17, // 4: cognee.ingestion.v1.DataPoint.fields:type_name -> google.protobuf.Struct
	6,  // 5: cognee.ingestion.v1.DataPoint.relations:type_name -> cognee.ingestion.v1.Relation
	9,  // 6: cognee.ingestion.v1.ListDatasetsResponse.datasets:type_name -> cognee.ingestion.v1.DatasetInfo
	12, // 7: cognee.ingestion.v1.ListDataEntriesResponse.entries:type_name -> cognee.ingestion.v1.DataEntryInfo
	0,  // 8: cognee.ingestion.v1.IngestionService.AddData:input_type -> cognee.ingestion.v1.AddDataRequest
	4,  // 9: cognee.ingestion.v1.IngestionService.AddDataPoints:input_type -> cognee.ingestion.v1.AddDataPointsRequest
	8,  // 10: cognee.ingestion.v1.IngestionService.ListDatasets:input_type -> cognee.ingestion.v1.ListDatasetsRequest
	11, // 11: cognee.ingestion.v1.IngestionService.ListDataEntries:input_type -> cognee.ingestion.v1.ListDataEntriesRequest
	14, // 12: cognee.ingestion.v1.IngestionService.DeleteDataset:input_type -> cognee.ingestion.v1.DeleteDatasetRequest
	3,  // 13: cognee.ingestion.v1.IngestionService.AddData:output_type -> cognee.ingestion.v1.AddDataResponse
	7,  // 14: cognee.ingestion.v1.IngestionService.AddDataPoints:output_type -> cognee.ingestion.v1.AddDataPointsResponse
	10, // 15: cognee.ingestion.v1.IngestionService.ListDatasets:output_type -> cognee.ingestion.v1.ListDatasetsResponse
	13, // 16: cognee.ingestion.v1.IngestionService.ListDataEntries:output_type -> cognee.ingestion.v1.ListDataEntriesResponse
	15, // 17: cognee.ingestion.v1.IngestionService.DeleteDataset:output_type -> cognee.ingestion.v1.DeleteDatasetResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_cognee_ingestion_v1_ingestion_proto_init() }
func file_api_proto_cognee_ingestion_v1_ingestion_proto_init() {
	if File_api_proto_cognee_ingestion_v1_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDesc), len(file_api_proto_cognee_ingestion_v1_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cognee_ingestion_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_api_proto_cognee_ingestion_v1_ingestion_proto_depIdxs,
		MessageInfos:      file_api_proto_cognee_ingestion_v1_ingestion_proto_msgTypes,
	}.Build()
	File_api_proto_cognee_ingestion_v1_ingestion_proto = out.File
	file_api_proto_cognee_ingestion_v1_ingestion_proto_goTypes = nil
	file_api_proto_cognee_ingestion_v1_ingestion_proto_depIdxs = nil
}
