// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: api/proto/observe/v1/observe.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObserveRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HookType          string                 `protobuf:"bytes,2,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"` // session_start|prompt_submit|pre_tool_use|post_tool_use|...
	ToolName          string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInput         []byte                 `protobuf:"bytes,4,opt,name=tool_input,json=toolInput,proto3" json:"tool_input,omitempty"`    // JSON
	ToolOutput        []byte                 `protobuf:"bytes,5,opt,name=tool_output,json=toolOutput,proto3" json:"tool_output,omitempty"` // JSON
	UserPrompt        string                 `protobuf:"bytes,6,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"`
	AssistantResponse string                 `protobuf:"bytes,7,opt,name=assistant_response,json=assistantResponse,proto3" json:"assistant_response,omitempty"`
	AgentId           string                 `protobuf:"bytes,8,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId          string                 `protobuf:"bytes,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Project           string                 `protobuf:"bytes,11,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{0}
}

func (x *ObserveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ObserveRequest) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

func (x *ObserveRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ObserveRequest) GetToolInput() []byte {
	if x != nil {
		return x.ToolInput
	}
	return nil
}

func (x *ObserveRequest) GetToolOutput() []byte {
	if x != nil {
		return x.ToolOutput
	}
	return nil
}

func (x *ObserveRequest) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *ObserveRequest) GetAssistantResponse() string {
	if x != nil {
		return x.AssistantResponse
	}
	return ""
}

func (x *ObserveRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ObserveRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ObserveRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ObserveRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type ObserveResponse struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	ObservationId   string                      `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	Deduplicated    bool                        `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	Compressed      *CompressedObservationProto `protobuf:"bytes,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
	InjectedContext string                      `protobuf:"bytes,4,opt,name=injected_context,json=injectedContext,proto3" json:"injected_context,omitempty"` // populated when hook=session_start + inject_context=true
	ContextTokens   int32                       `protobuf:"varint,5,opt,name=context_tokens,json=contextTokens,proto3" json:"context_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{1}
}

func (x *ObserveResponse) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *ObserveResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

func (x *ObserveResponse) GetCompressed() *CompressedObservationProto {
	if x != nil {
		return x.Compressed
	}
	return nil
}

func (x *ObserveResponse) GetInjectedContext() string {
	if x != nil {
		return x.InjectedContext
	}
	return ""
}

func (x *ObserveResponse) GetContextTokens() int32 {
	if x != nil {
		return x.ContextTokens
	}
	return 0
}

type CompressedObservationProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObsType       string                 `protobuf:"bytes,2,opt,name=obs_type,json=obsType,proto3" json:"obs_type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      string                 `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Facts         []string               `protobuf:"bytes,5,rep,name=facts,proto3" json:"facts,omitempty"`
	Narrative     string                 `protobuf:"bytes,6,opt,name=narrative,proto3" json:"narrative,omitempty"`
	Concepts      []string               `protobuf:"bytes,7,rep,name=concepts,proto3" json:"concepts,omitempty"`
	Files         []string               `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"`
	Importance    float64                `protobuf:"fixed64,9,opt,name=importance,proto3" json:"importance,omitempty"`
	Confidence    float64                `protobuf:"fixed64,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AgentId       string                 `protobuf:"bytes,11,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressedObservationProto) Reset() {
	*x = CompressedObservationProto{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressedObservationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedObservationProto) ProtoMessage() {}

func (x *CompressedObservationProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedObservationProto.ProtoReflect.Descriptor instead.
func (*CompressedObservationProto) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{2}
}

func (x *CompressedObservationProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompressedObservationProto) GetObsType() string {
	if x != nil {
		return x.ObsType
	}
	return ""
}

func (x *CompressedObservationProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CompressedObservationProto) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *CompressedObservationProto) GetFacts() []string {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *CompressedObservationProto) GetNarrative() string {
	if x != nil {
		return x.Narrative
	}
	return ""
}

func (x *CompressedObservationProto) GetConcepts() []string {
	if x != nil {
		return x.Concepts
	}
	return nil
}

func (x *CompressedObservationProto) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *CompressedObservationProto) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *CompressedObservationProto) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CompressedObservationProto) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CompressedObservationProto) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FirstPrompt   string                 `protobuf:"bytes,6,opt,name=first_prompt,json=firstPrompt,proto3" json:"first_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{3}
}

func (x *StartSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StartSessionRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *StartSessionRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartSessionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StartSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StartSessionRequest) GetFirstPrompt() string {
	if x != nil {
		return x.FirstPrompt
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{4}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type EndSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // completed
	ObservationCount int32                  `protobuf:"varint,3,opt,name=observation_count,json=observationCount,proto3" json:"observation_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{6}
}

func (x *EndSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EndSessionResponse) GetObservationCount() int32 {
	if x != nil {
		return x.ObservationCount
	}
	return 0
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSessionResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SessionProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Project          string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Cwd              string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Model            string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	AgentId          string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Summary          string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	ObservationCount int32                  `protobuf:"varint,9,opt,name=observation_count,json=observationCount,proto3" json:"observation_count,omitempty"`
	Tags             []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	LastActiveAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionProto) Reset() {
	*x = SessionProto{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionProto) ProtoMessage() {}

func (x *SessionProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionProto.ProtoReflect.Descriptor instead.
func (*SessionProto) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{10}
}

func (x *SessionProto) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionProto) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SessionProto) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SessionProto) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SessionProto) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SessionProto) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionProto) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SessionProto) GetObservationCount() int32 {
	if x != nil {
		return x.ObservationCount
	}
	return 0
}

func (x *SessionProto) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SessionProto) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SessionProto) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *SessionProto) GetLastActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveAt
	}
	return nil
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionProto          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{11}
}

func (x *GetSessionResponse) GetSession() *SessionProto {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "active" | "completed" | ""
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{12}
}

func (x *ListSessionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListSessionsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionProto        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{13}
}

func (x *ListSessionsResponse) GetSessions() []*SessionProto {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetObservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Compressed    bool                   `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"` // true = compressed obs, false = raw obs
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationsRequest) Reset() {
	*x = GetObservationsRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsRequest) ProtoMessage() {}

func (x *GetObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsRequest.ProtoReflect.Descriptor instead.
func (*GetObservationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{14}
}

func (x *GetObservationsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetObservationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetObservationsRequest) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *GetObservationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetObservationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetObservationsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Observations  []*CompressedObservationProto `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationsResponse) Reset() {
	*x = GetObservationsResponse{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse) ProtoMessage() {}

func (x *GetObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsResponse.ProtoReflect.Descriptor instead.
func (*GetObservationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{15}
}

func (x *GetObservationsResponse) GetObservations() []*CompressedObservationProto {
	if x != nil {
		return x.Observations
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // empty = all sessions for tenant
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{16}
}

func (x *StreamEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamEventsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type StreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // raw_observation | session_started | session_ended
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // JSON
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observe_v1_observe_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_observe_v1_observe_proto_rawDescGZIP(), []int{17}
}

func (x *StreamEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StreamEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_proto_observe_v1_observe_proto protoreflect.FileDescriptor

const file_api_proto_observe_v1_observe_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/observe/v1/observe.proto\x12\n" +
	"observe.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\x0eObserveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\thook_type\x18\x02 \x01(\tR\bhookType\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"tool_input\x18\x04 \x01(\fR\ttoolInput\x12\x1f\n" +
	"\vtool_output\x18\x05 \x01(\fR\n" +
	"toolOutput\x12\x1f\n" +
	"\vuser_prompt\x18\x06 \x01(\tR\n" +
	"userPrompt\x12-\n" +
	"\x12assistant_response\x18\a \x01(\tR\x11assistantResponse\x12\x19\n" +
	"\bagent_id\x18\b \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\t \x01(\tR\btenantId\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aproject\x18\v \x01(\tR\aproject\"\xf6\x01\n" +
	"\x0fObserveResponse\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\x12F\n" +
	"\n" +
	"compressed\x18\x03 \x01(\v2&.observe.v1.CompressedObservationProtoR\n" +
	"compressed\x12)\n" +
	"\x10injected_context\x18\x04 \x01(\tR\x0finjectedContext\x12%\n" +
	"\x0econtext_tokens\x18\x05 \x01(\x05R\rcontextTokens\"\xf4\x02\n" +
	"\x1aCompressedObservationProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bobs_type\x18\x02 \x01(\tR\aobsType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x04 \x01(\tR\bsubtitle\x12\x14\n" +
	"\x05facts\x18\x05 \x03(\tR\x05facts\x12\x1c\n" +
	"\tnarrative\x18\x06 \x01(\tR\tnarrative\x12\x1a\n" +
	"\bconcepts\x18\a \x03(\tR\bconcepts\x12\x14\n" +
	"\x05files\x18\b \x03(\tR\x05files\x12\x1e\n" +
	"\n" +
	"importance\x18\t \x01(\x01R\n" +
	"importance\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x01R\n" +
	"confidence\x12\x19\n" +
	"\bagent_id\x18\v \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb2\x01\n" +
	"\x13StartSessionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12!\n" +
	"\ffirst_prompt\x18\x06 \x01(\tR\vfirstPrompt\"M\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"O\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"x\n" +
	"\x12EndSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12+\n" +
	"\x11observation_count\x18\x03 \x01(\x05R\x10observationCount\"O\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"R\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xce\x03\n" +
	"\fSessionProto\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12+\n" +
	"\x11observation_count\x18\t \x01(\x05R\x10observationCount\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12@\n" +
	"\x0elast_active_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\flastActiveAt\"H\n" +
	"\x12GetSessionResponse\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.observe.v1.SessionProtoR\asession\"\x92\x01\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"L\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.observe.v1.SessionProtoR\bsessions\"\xa2\x01\n" +
	"\x16GetObservationsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1e\n" +
	"\n" +
	"compressed\x18\x03 \x01(\bR\n" +
	"compressed\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"e\n" +
	"\x17GetObservationsResponse\x12J\n" +
	"\fobservations\x18\x01 \x03(\v2&.observe.v1.CompressedObservationProtoR\fobservations\"Q\n" +
	"\x13StreamEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"z\n" +
	"\vStreamEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x92\x05\n" +
	"\x0eObserveService\x12B\n" +
	"\aObserve\x12\x1a.observe.v1.ObserveRequest\x1a\x1b.observe.v1.ObserveResponse\x12Q\n" +
	"\fStartSession\x12\x1f.observe.v1.StartSessionRequest\x1a .observe.v1.StartSessionResponse\x12K\n" +
	"\n" +
	"EndSession\x12\x1d.observe.v1.EndSessionRequest\x1a\x1e.observe.v1.EndSessionResponse\x12K\n" +
	"\n" +
	"GetSession\x12\x1d.observe.v1.GetSessionRequest\x1a\x1e.observe.v1.GetSessionResponse\x12Q\n" +
	"\fListSessions\x12\x1f.observe.v1.ListSessionsRequest\x1a .observe.v1.ListSessionsResponse\x12Z\n" +
	"\x0fGetObservations\x12\".observe.v1.GetObservationsRequest\x1a#.observe.v1.GetObservationsResponse\x12T\n" +
	"\rDeleteSession\x12 .observe.v1.DeleteSessionRequest\x1a!.observe.v1.DeleteSessionResponse\x12J\n" +
	"\fStreamEvents\x12\x1f.observe.v1.StreamEventsRequest\x1a\x17.observe.v1.StreamEvent0\x01B,Z*github.com/vnp-memory/api/proto/observe/v1b\x06proto3"

var (
	file_api_proto_observe_v1_observe_proto_rawDescOnce sync.Once
	file_api_proto_observe_v1_observe_proto_rawDescData []byte
)

func file_api_proto_observe_v1_observe_proto_rawDescGZIP() []byte {
	file_api_proto_observe_v1_observe_proto_rawDescOnce.Do(func() {
		file_api_proto_observe_v1_observe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_observe_v1_observe_proto_rawDesc), len(file_api_proto_observe_v1_observe_proto_rawDesc)))
	})
	return file_api_proto_observe_v1_observe_proto_rawDescData
}

var file_api_proto_observe_v1_observe_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_observe_v1_observe_proto_goTypes = []any{
	(*ObserveRequest)(nil),             // 0: observe.v1.ObserveRequest
	(*ObserveResponse)(nil),            // 1: observe.v1.ObserveResponse
	(*CompressedObservationProto)(nil), // 2: observe.v1.CompressedObservationProto
	(*StartSessionRequest)(nil),        // 3: observe.v1.StartSessionRequest
	(*StartSessionResponse)(nil),       // 4: observe.v1.StartSessionResponse
	(*EndSessionRequest)(nil),          // 5: observe.v1.EndSessionRequest
	(*EndSessionResponse)(nil),         // 6: observe.v1.EndSessionResponse
	(*GetSessionRequest)(nil),          // 7: observe.v1.GetSessionRequest
	(*DeleteSessionRequest)(nil),       // 8: observe.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),      // 9: observe.v1.DeleteSessionResponse
	(*SessionProto)(nil),               // 10: observe.v1.SessionProto
	(*GetSessionResponse)(nil),         // 11: observe.v1.GetSessionResponse
	(*ListSessionsRequest)(nil),        // 12: observe.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),       // 13: observe.v1.ListSessionsResponse
	(*GetObservationsRequest)(nil),     // 14: observe.v1.GetObservationsRequest
	(*GetObservationsResponse)(nil),    // 15: observe.v1.GetObservationsResponse
	(*StreamEventsRequest)(nil),        // 16: observe.v1.StreamEventsRequest
	(*StreamEvent)(nil),                // 17: observe.v1.StreamEvent
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
}
var file_api_proto_observe_v1_observe_proto_depIdxs = []int32{
	18, // 0: observe.v1.ObserveRequest.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: observe.v1.ObserveResponse.compressed:type_name -> observe.v1.CompressedObservationProto
	18, // 2: observe.v1.CompressedObservationProto.timestamp:type_name -> google.protobuf.Timestamp
	18, // 3: observe.v1.SessionProto.started_at:type_name -> google.protobuf.Timestamp
	18, // 4: observe.v1.SessionProto.ended_at:type_name -> google.protobuf.Timestamp
	18, // 5: observe.v1.SessionProto.last_active_at:type_name -> google.protobuf.Timestamp
	10, // 6: observe.v1.GetSessionResponse.session:type_name -> observe.v1.SessionProto
	10, // 7: observe.v1.ListSessionsResponse.sessions:type_name -> observe.v1.SessionProto
	2,  // 8: observe.v1.GetObservationsResponse.observations:type_name -> observe.v1.CompressedObservationProto
	18, // 9: observe.v1.StreamEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 10: observe.v1.ObserveService.Observe:input_type -> observe.v1.ObserveRequest
	3,  // 11: observe.v1.ObserveService.StartSession:input_type -> observe.v1.StartSessionRequest
	5,  // 12: observe.v1.ObserveService.EndSession:input_type -> observe.v1.EndSessionRequest
	7,  // 13: observe.v1.ObserveService.GetSession:input_type -> observe.v1.GetSessionRequest
	12, // 14: observe.v1.ObserveService.ListSessions:input_type -> observe.v1.ListSessionsRequest
	14, // 15: observe.v1.ObserveService.GetObservations:input_type -> observe.v1.GetObservationsRequest
	8,  // 16: observe.v1.ObserveService.DeleteSession:input_type -> observe.v1.DeleteSessionRequest
	16, // 17: observe.v1.ObserveService.StreamEvents:input_type -> observe.v1.StreamEventsRequest
	1,  // 18: observe.v1.ObserveService.Observe:output_type -> observe.v1.ObserveResponse
	4,  // 19: observe.v1.ObserveService.StartSession:output_type -> observe.v1.StartSessionResponse
	6,  // 20: observe.v1.ObserveService.EndSession:output_type -> observe.v1.EndSessionResponse
	11, // 21: observe.v1.ObserveService.GetSession:output_type -> observe.v1.GetSessionResponse
	13, // 22: observe.v1.ObserveService.ListSessions:output_type -> observe.v1.ListSessionsResponse
	15, // 23: observe.v1.ObserveService.GetObservations:output_type -> observe.v1.GetObservationsResponse
	9,  // 24: observe.v1.ObserveService.DeleteSession:output_type -> observe.v1.DeleteSessionResponse
	17, // 25: observe.v1.ObserveService.StreamEvents:output_type -> observe.v1.StreamEvent
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_observe_v1_observe_proto_init() }
func file_api_proto_observe_v1_observe_proto_init() {
	if File_api_proto_observe_v1_observe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_observe_v1_observe_proto_rawDesc), len(file_api_proto_observe_v1_observe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_observe_v1_observe_proto_goTypes,
		DependencyIndexes: file_api_proto_observe_v1_observe_proto_depIdxs,
		MessageInfos:      file_api_proto_observe_v1_observe_proto_msgTypes,
	}.Build()
	File_api_proto_observe_v1_observe_proto = out.File
	file_api_proto_observe_v1_observe_proto_goTypes = nil
	file_api_proto_observe_v1_observe_proto_depIdxs = nil
}
