// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: accesscontrol/v1/policy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessControl_CreatePolicy_FullMethodName = "/api.accesscontrol.v1.AccessControl/CreatePolicy"
	AccessControl_ListPolicies_FullMethodName = "/api.accesscontrol.v1.AccessControl/ListPolicies"
	AccessControl_GetPolicy_FullMethodName    = "/api.accesscontrol.v1.AccessControl/GetPolicy"
)

// AccessControlClient is the client API for AccessControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessControlClient interface {
	// Create a new OPA Policy
	CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*PolicyReply, error)
	// List all policies for the app
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesReply, error)
	// Get a specific policy
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*PolicyReply, error)
}

type accessControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessControlClient(cc grpc.ClientConnInterface) AccessControlClient {
	return &accessControlClient{cc}
}

func (c *accessControlClient) CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*PolicyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyReply)
	err := c.cc.Invoke(ctx, AccessControl_CreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesReply)
	err := c.cc.Invoke(ctx, AccessControl_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*PolicyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyReply)
	err := c.cc.Invoke(ctx, AccessControl_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessControlServer is the server API for AccessControl service.
// All implementations must embed UnimplementedAccessControlServer
// for forward compatibility.
type AccessControlServer interface {
	// Create a new OPA Policy
	CreatePolicy(context.Context, *CreatePolicyRequest) (*PolicyReply, error)
	// List all policies for the app
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesReply, error)
	// Get a specific policy
	GetPolicy(context.Context, *GetPolicyRequest) (*PolicyReply, error)
	mustEmbedUnimplementedAccessControlServer()
}

// UnimplementedAccessControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessControlServer struct{}

func (UnimplementedAccessControlServer) CreatePolicy(context.Context, *CreatePolicyRequest) (*PolicyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePolicy not implemented")
}
func (UnimplementedAccessControlServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedAccessControlServer) GetPolicy(context.Context, *GetPolicyRequest) (*PolicyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedAccessControlServer) mustEmbedUnimplementedAccessControlServer() {}
func (UnimplementedAccessControlServer) testEmbeddedByValue()                       {}

// UnsafeAccessControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessControlServer will
// result in compilation errors.
type UnsafeAccessControlServer interface {
	mustEmbedUnimplementedAccessControlServer()
}

func RegisterAccessControlServer(s grpc.ServiceRegistrar, srv AccessControlServer) {
	// If the following call panics, it indicates UnimplementedAccessControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessControl_ServiceDesc, srv)
}

func _AccessControl_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControl_CreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).CreatePolicy(ctx, req.(*CreatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControl_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControl_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessControl_ServiceDesc is the grpc.ServiceDesc for AccessControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.accesscontrol.v1.AccessControl",
	HandlerType: (*AccessControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePolicy",
			Handler:    _AccessControl_CreatePolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _AccessControl_ListPolicies_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _AccessControl_GetPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accesscontrol/v1/policy.proto",
}
