// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.12.4
// source: accesscontrol/v1/policy.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAccessControlCreatePolicy = "/api.accesscontrol.v1.AccessControl/CreatePolicy"
const OperationAccessControlGetPolicy = "/api.accesscontrol.v1.AccessControl/GetPolicy"
const OperationAccessControlListPolicies = "/api.accesscontrol.v1.AccessControl/ListPolicies"

type AccessControlHTTPServer interface {
	// CreatePolicy Create a new OPA Policy
	CreatePolicy(context.Context, *CreatePolicyRequest) (*PolicyReply, error)
	// GetPolicy Get a specific policy
	GetPolicy(context.Context, *GetPolicyRequest) (*PolicyReply, error)
	// ListPolicies List all policies for the app
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesReply, error)
}

func RegisterAccessControlHTTPServer(s *http.Server, srv AccessControlHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/policies", _AccessControl_CreatePolicy0_HTTP_Handler(srv))
	r.GET("/v1/policies", _AccessControl_ListPolicies0_HTTP_Handler(srv))
	r.GET("/v1/policies/{id}", _AccessControl_GetPolicy0_HTTP_Handler(srv))
}

func _AccessControl_CreatePolicy0_HTTP_Handler(srv AccessControlHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePolicyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccessControlCreatePolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePolicy(ctx, req.(*CreatePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PolicyReply)
		return ctx.Result(200, reply)
	}
}

func _AccessControl_ListPolicies0_HTTP_Handler(srv AccessControlHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPoliciesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccessControlListPolicies)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPolicies(ctx, req.(*ListPoliciesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPoliciesReply)
		return ctx.Result(200, reply)
	}
}

func _AccessControl_GetPolicy0_HTTP_Handler(srv AccessControlHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPolicyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccessControlGetPolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPolicy(ctx, req.(*GetPolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PolicyReply)
		return ctx.Result(200, reply)
	}
}

type AccessControlHTTPClient interface {
	// CreatePolicy Create a new OPA Policy
	CreatePolicy(ctx context.Context, req *CreatePolicyRequest, opts ...http.CallOption) (rsp *PolicyReply, err error)
	// GetPolicy Get a specific policy
	GetPolicy(ctx context.Context, req *GetPolicyRequest, opts ...http.CallOption) (rsp *PolicyReply, err error)
	// ListPolicies List all policies for the app
	ListPolicies(ctx context.Context, req *ListPoliciesRequest, opts ...http.CallOption) (rsp *ListPoliciesReply, err error)
}

type AccessControlHTTPClientImpl struct {
	cc *http.Client
}

func NewAccessControlHTTPClient(client *http.Client) AccessControlHTTPClient {
	return &AccessControlHTTPClientImpl{client}
}

// CreatePolicy Create a new OPA Policy
func (c *AccessControlHTTPClientImpl) CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...http.CallOption) (*PolicyReply, error) {
	var out PolicyReply
	pattern := "/v1/policies"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccessControlCreatePolicy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPolicy Get a specific policy
func (c *AccessControlHTTPClientImpl) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...http.CallOption) (*PolicyReply, error) {
	var out PolicyReply
	pattern := "/v1/policies/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccessControlGetPolicy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPolicies List all policies for the app
func (c *AccessControlHTTPClientImpl) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...http.CallOption) (*ListPoliciesReply, error) {
	var out ListPoliciesReply
	pattern := "/v1/policies"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccessControlListPolicies))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
