// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.12.4
// source: graph/v1/graph.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGraphBatchUpsertEntities = "/api.graph.v1.Graph/BatchUpsertEntities"
const OperationGraphCreateEdge = "/api.graph.v1.Graph/CreateEdge"
const OperationGraphCreateNode = "/api.graph.v1.Graph/CreateNode"
const OperationGraphGetContext = "/api.graph.v1.Graph/GetContext"
const OperationGraphGetCoverage = "/api.graph.v1.Graph/GetCoverage"
const OperationGraphGetImpact = "/api.graph.v1.Graph/GetImpact"
const OperationGraphGetNode = "/api.graph.v1.Graph/GetNode"
const OperationGraphGetSubgraph = "/api.graph.v1.Graph/GetSubgraph"
const OperationGraphHybridSearch = "/api.graph.v1.Graph/HybridSearch"

type GraphHTTPServer interface {
	// BatchUpsertEntities Batch upsert entities
	BatchUpsertEntities(context.Context, *BatchUpsertRequest) (*BatchUpsertReply, error)
	// CreateEdge Create an edge between two nodes
	CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeReply, error)
	// CreateNode Create a new node in the Knowledge Graph
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeReply, error)
	// GetContext Get contextual neighborhood around a node
	GetContext(context.Context, *GetContextRequest) (*GraphReply, error)
	// GetCoverage Get upstream coverage of a node
	GetCoverage(context.Context, *GetCoverageRequest) (*GraphReply, error)
	// GetImpact Get downstream impact of a node
	GetImpact(context.Context, *GetImpactRequest) (*GraphReply, error)
	// GetNode Get a node by ID
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	// GetSubgraph Get subgraph for a list of node IDs
	GetSubgraph(context.Context, *GetSubgraphRequest) (*GraphReply, error)
	// HybridSearch Hybrid search across vector and full-text indexes
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchReply, error)
}

func RegisterGraphHTTPServer(s *http.Server, srv GraphHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/graph/nodes", _Graph_CreateNode0_HTTP_Handler(srv))
	r.GET("/v1/graph/nodes/{node_id}", _Graph_GetNode0_HTTP_Handler(srv))
	r.POST("/v1/graph/edges", _Graph_CreateEdge0_HTTP_Handler(srv))
	r.GET("/v1/graph/nodes/{node_id}/context", _Graph_GetContext0_HTTP_Handler(srv))
	r.GET("/v1/graph/nodes/{node_id}/impact", _Graph_GetImpact0_HTTP_Handler(srv))
	r.GET("/v1/graph/nodes/{node_id}/coverage", _Graph_GetCoverage0_HTTP_Handler(srv))
	r.POST("/v1/graph/subgraph", _Graph_GetSubgraph0_HTTP_Handler(srv))
	r.POST("/v1/graph/entities/batch", _Graph_BatchUpsertEntities0_HTTP_Handler(srv))
	r.POST("/v1/graph/search/hybrid", _Graph_HybridSearch0_HTTP_Handler(srv))
}

func _Graph_CreateNode0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphCreateNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNode(ctx, req.(*CreateNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNodeReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_GetNode0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphGetNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNode(ctx, req.(*GetNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetNodeReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_CreateEdge0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEdgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphCreateEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEdge(ctx, req.(*CreateEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEdgeReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_GetContext0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetContextRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphGetContext)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContext(ctx, req.(*GetContextRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GraphReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_GetImpact0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetImpactRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphGetImpact)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetImpact(ctx, req.(*GetImpactRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GraphReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_GetCoverage0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCoverageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphGetCoverage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCoverage(ctx, req.(*GetCoverageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GraphReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_GetSubgraph0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSubgraphRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphGetSubgraph)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSubgraph(ctx, req.(*GetSubgraphRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GraphReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_BatchUpsertEntities0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchUpsertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphBatchUpsertEntities)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchUpsertEntities(ctx, req.(*BatchUpsertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchUpsertReply)
		return ctx.Result(200, reply)
	}
}

func _Graph_HybridSearch0_HTTP_Handler(srv GraphHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HybridSearchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGraphHybridSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HybridSearch(ctx, req.(*HybridSearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HybridSearchReply)
		return ctx.Result(200, reply)
	}
}

type GraphHTTPClient interface {
	// BatchUpsertEntities Batch upsert entities
	BatchUpsertEntities(ctx context.Context, req *BatchUpsertRequest, opts ...http.CallOption) (rsp *BatchUpsertReply, err error)
	// CreateEdge Create an edge between two nodes
	CreateEdge(ctx context.Context, req *CreateEdgeRequest, opts ...http.CallOption) (rsp *CreateEdgeReply, err error)
	// CreateNode Create a new node in the Knowledge Graph
	CreateNode(ctx context.Context, req *CreateNodeRequest, opts ...http.CallOption) (rsp *CreateNodeReply, err error)
	// GetContext Get contextual neighborhood around a node
	GetContext(ctx context.Context, req *GetContextRequest, opts ...http.CallOption) (rsp *GraphReply, err error)
	// GetCoverage Get upstream coverage of a node
	GetCoverage(ctx context.Context, req *GetCoverageRequest, opts ...http.CallOption) (rsp *GraphReply, err error)
	// GetImpact Get downstream impact of a node
	GetImpact(ctx context.Context, req *GetImpactRequest, opts ...http.CallOption) (rsp *GraphReply, err error)
	// GetNode Get a node by ID
	GetNode(ctx context.Context, req *GetNodeRequest, opts ...http.CallOption) (rsp *GetNodeReply, err error)
	// GetSubgraph Get subgraph for a list of node IDs
	GetSubgraph(ctx context.Context, req *GetSubgraphRequest, opts ...http.CallOption) (rsp *GraphReply, err error)
	// HybridSearch Hybrid search across vector and full-text indexes
	HybridSearch(ctx context.Context, req *HybridSearchRequest, opts ...http.CallOption) (rsp *HybridSearchReply, err error)
}

type GraphHTTPClientImpl struct {
	cc *http.Client
}

func NewGraphHTTPClient(client *http.Client) GraphHTTPClient {
	return &GraphHTTPClientImpl{client}
}

// BatchUpsertEntities Batch upsert entities
func (c *GraphHTTPClientImpl) BatchUpsertEntities(ctx context.Context, in *BatchUpsertRequest, opts ...http.CallOption) (*BatchUpsertReply, error) {
	var out BatchUpsertReply
	pattern := "/v1/graph/entities/batch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGraphBatchUpsertEntities))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateEdge Create an edge between two nodes
func (c *GraphHTTPClientImpl) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...http.CallOption) (*CreateEdgeReply, error) {
	var out CreateEdgeReply
	pattern := "/v1/graph/edges"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGraphCreateEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateNode Create a new node in the Knowledge Graph
func (c *GraphHTTPClientImpl) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...http.CallOption) (*CreateNodeReply, error) {
	var out CreateNodeReply
	pattern := "/v1/graph/nodes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGraphCreateNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetContext Get contextual neighborhood around a node
func (c *GraphHTTPClientImpl) GetContext(ctx context.Context, in *GetContextRequest, opts ...http.CallOption) (*GraphReply, error) {
	var out GraphReply
	pattern := "/v1/graph/nodes/{node_id}/context"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGraphGetContext))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCoverage Get upstream coverage of a node
func (c *GraphHTTPClientImpl) GetCoverage(ctx context.Context, in *GetCoverageRequest, opts ...http.CallOption) (*GraphReply, error) {
	var out GraphReply
	pattern := "/v1/graph/nodes/{node_id}/coverage"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGraphGetCoverage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetImpact Get downstream impact of a node
func (c *GraphHTTPClientImpl) GetImpact(ctx context.Context, in *GetImpactRequest, opts ...http.CallOption) (*GraphReply, error) {
	var out GraphReply
	pattern := "/v1/graph/nodes/{node_id}/impact"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGraphGetImpact))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNode Get a node by ID
func (c *GraphHTTPClientImpl) GetNode(ctx context.Context, in *GetNodeRequest, opts ...http.CallOption) (*GetNodeReply, error) {
	var out GetNodeReply
	pattern := "/v1/graph/nodes/{node_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGraphGetNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSubgraph Get subgraph for a list of node IDs
func (c *GraphHTTPClientImpl) GetSubgraph(ctx context.Context, in *GetSubgraphRequest, opts ...http.CallOption) (*GraphReply, error) {
	var out GraphReply
	pattern := "/v1/graph/subgraph"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGraphGetSubgraph))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HybridSearch Hybrid search across vector and full-text indexes
func (c *GraphHTTPClientImpl) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...http.CallOption) (*HybridSearchReply, error) {
	var out HybridSearchReply
	pattern := "/v1/graph/search/hybrid"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGraphHybridSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
