// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: graph/v1/graph.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Graph_CreateNode_FullMethodName  = "/api.graph.v1.Graph/CreateNode"
	Graph_GetNode_FullMethodName     = "/api.graph.v1.Graph/GetNode"
	Graph_CreateEdge_FullMethodName  = "/api.graph.v1.Graph/CreateEdge"
	Graph_GetContext_FullMethodName  = "/api.graph.v1.Graph/GetContext"
	Graph_GetImpact_FullMethodName   = "/api.graph.v1.Graph/GetImpact"
	Graph_GetCoverage_FullMethodName = "/api.graph.v1.Graph/GetCoverage"
	Graph_GetSubgraph_FullMethodName = "/api.graph.v1.Graph/GetSubgraph"
)

// GraphClient is the client API for Graph service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphClient interface {
	// Create a new node in the Knowledge Graph
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeReply, error)
	// Get a node by ID
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error)
	// Create an edge between two nodes
	CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*CreateEdgeReply, error)
	// Get contextual neighborhood around a node
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GraphReply, error)
	// Get downstream impact of a node
	GetImpact(ctx context.Context, in *GetImpactRequest, opts ...grpc.CallOption) (*GraphReply, error)
	// Get upstream coverage of a node
	GetCoverage(ctx context.Context, in *GetCoverageRequest, opts ...grpc.CallOption) (*GraphReply, error)
	// Get subgraph for a list of node IDs
	GetSubgraph(ctx context.Context, in *GetSubgraphRequest, opts ...grpc.CallOption) (*GraphReply, error)
}

type graphClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphClient(cc grpc.ClientConnInterface) GraphClient {
	return &graphClient{cc}
}

func (c *graphClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeReply)
	err := c.cc.Invoke(ctx, Graph_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeReply)
	err := c.cc.Invoke(ctx, Graph_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphClient) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*CreateEdgeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEdgeReply)
	err := c.cc.Invoke(ctx, Graph_CreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GraphReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphReply)
	err := c.cc.Invoke(ctx, Graph_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphClient) GetImpact(ctx context.Context, in *GetImpactRequest, opts ...grpc.CallOption) (*GraphReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphReply)
	err := c.cc.Invoke(ctx, Graph_GetImpact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphClient) GetCoverage(ctx context.Context, in *GetCoverageRequest, opts ...grpc.CallOption) (*GraphReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphReply)
	err := c.cc.Invoke(ctx, Graph_GetCoverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphClient) GetSubgraph(ctx context.Context, in *GetSubgraphRequest, opts ...grpc.CallOption) (*GraphReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphReply)
	err := c.cc.Invoke(ctx, Graph_GetSubgraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServer is the server API for Graph service.
// All implementations must embed UnimplementedGraphServer
// for forward compatibility.
type GraphServer interface {
	// Create a new node in the Knowledge Graph
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeReply, error)
	// Get a node by ID
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	// Create an edge between two nodes
	CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeReply, error)
	// Get contextual neighborhood around a node
	GetContext(context.Context, *GetContextRequest) (*GraphReply, error)
	// Get downstream impact of a node
	GetImpact(context.Context, *GetImpactRequest) (*GraphReply, error)
	// Get upstream coverage of a node
	GetCoverage(context.Context, *GetCoverageRequest) (*GraphReply, error)
	// Get subgraph for a list of node IDs
	GetSubgraph(context.Context, *GetSubgraphRequest) (*GraphReply, error)
	mustEmbedUnimplementedGraphServer()
}

// UnimplementedGraphServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServer struct{}

func (UnimplementedGraphServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedGraphServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedGraphServer) CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEdge not implemented")
}
func (UnimplementedGraphServer) GetContext(context.Context, *GetContextRequest) (*GraphReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedGraphServer) GetImpact(context.Context, *GetImpactRequest) (*GraphReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImpact not implemented")
}
func (UnimplementedGraphServer) GetCoverage(context.Context, *GetCoverageRequest) (*GraphReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoverage not implemented")
}
func (UnimplementedGraphServer) GetSubgraph(context.Context, *GetSubgraphRequest) (*GraphReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubgraph not implemented")
}
func (UnimplementedGraphServer) mustEmbedUnimplementedGraphServer() {}
func (UnimplementedGraphServer) testEmbeddedByValue()               {}

// UnsafeGraphServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServer will
// result in compilation errors.
type UnsafeGraphServer interface {
	mustEmbedUnimplementedGraphServer()
}

func RegisterGraphServer(s grpc.ServiceRegistrar, srv GraphServer) {
	// If the following call panics, it indicates UnimplementedGraphServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Graph_ServiceDesc, srv)
}

func _Graph_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graph_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Graph_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graph_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Graph_CreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).CreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graph_CreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).CreateEdge(ctx, req.(*CreateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Graph_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graph_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Graph_GetImpact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImpactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).GetImpact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graph_GetImpact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).GetImpact(ctx, req.(*GetImpactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Graph_GetCoverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).GetCoverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graph_GetCoverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).GetCoverage(ctx, req.(*GetCoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Graph_GetSubgraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubgraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).GetSubgraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graph_GetSubgraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).GetSubgraph(ctx, req.(*GetSubgraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Graph_ServiceDesc is the grpc.ServiceDesc for Graph service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Graph_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.graph.v1.Graph",
	HandlerType: (*GraphServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _Graph_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Graph_GetNode_Handler,
		},
		{
			MethodName: "CreateEdge",
			Handler:    _Graph_CreateEdge_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _Graph_GetContext_Handler,
		},
		{
			MethodName: "GetImpact",
			Handler:    _Graph_GetImpact_Handler,
		},
		{
			MethodName: "GetCoverage",
			Handler:    _Graph_GetCoverage_Handler,
		},
		{
			MethodName: "GetSubgraph",
			Handler:    _Graph_GetSubgraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph/v1/graph.proto",
}
