-- Rollback: 0042_orchestration.down.sql
DROP TABLE IF EXISTS crystals CASCADE;
DROP TABLE IF EXISTS sketches CASCADE;
DROP TABLE IF EXISTS sentinels CASCADE;
DROP TABLE IF EXISTS checkpoints CASCADE;
DROP TABLE IF EXISTS routines CASCADE;
DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS leases CASCADE;
DROP TABLE IF EXISTS actions CASCADE;
