// Code generated by hand to fill gaps between kgs-platform's graph_http.pb.go
// and the newer graph.pb.go copied from doc-to-kg/third_party.
// These types exist in the original kgs-platform proto but were omitted from
// the doc-to-kg third_party copy (which only needs Merge* and Query).
package v1

// ── DeleteNode ────────────────────────────────────────────────────────────────

type DeleteNodeRequest struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AppId  string `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *DeleteNodeRequest) Reset()         {}
func (x *DeleteNodeRequest) String() string { return x.NodeId }
func (*DeleteNodeRequest) ProtoMessage()    {}
func (x *DeleteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}
func (x *DeleteNodeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type DeleteNodeReply struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteNodeReply) Reset()         {}
func (x *DeleteNodeReply) String() string { return "" }
func (*DeleteNodeReply) ProtoMessage()    {}
func (x *DeleteNodeReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ── UpdateNode ────────────────────────────────────────────────────────────────

type UpdateNodeRequest struct {
	NodeId     string            `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AppId      string            `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Properties map[string]string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateNodeRequest) Reset()         {}
func (x *UpdateNodeRequest) String() string { return x.NodeId }
func (*UpdateNodeRequest) ProtoMessage()    {}
func (x *UpdateNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}
func (x *UpdateNodeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}
func (x *UpdateNodeRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UpdateNodeReply struct {
	Node *GraphNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *UpdateNodeReply) Reset()         {}
func (x *UpdateNodeReply) String() string { return "" }
func (*UpdateNodeReply) ProtoMessage()    {}
func (x *UpdateNodeReply) GetNode() *GraphNode {
	if x != nil {
		return x.Node
	}
	return nil
}
