// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.12.4
// source: ontology/v1/ontology.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOntologyCreateEntityType = "/api.ontology.v1.Ontology/CreateEntityType"
const OperationOntologyCreateRelationType = "/api.ontology.v1.Ontology/CreateRelationType"
const OperationOntologyListEntityTypes = "/api.ontology.v1.Ontology/ListEntityTypes"
const OperationOntologyListRelationTypes = "/api.ontology.v1.Ontology/ListRelationTypes"

type OntologyHTTPServer interface {
	// CreateEntityType Define a new EntityType in the Knowledge Graph
	CreateEntityType(context.Context, *CreateEntityTypeRequest) (*CreateEntityTypeReply, error)
	// CreateRelationType Define a new RelationType in the Knowledge Graph
	CreateRelationType(context.Context, *CreateRelationTypeRequest) (*CreateRelationTypeReply, error)
	// ListEntityTypes Get schema definitions for EntityTypes
	ListEntityTypes(context.Context, *ListEntityTypesRequest) (*ListEntityTypesReply, error)
	// ListRelationTypes Get schema definitions for RelationTypes
	ListRelationTypes(context.Context, *ListRelationTypesRequest) (*ListRelationTypesReply, error)
}

func RegisterOntologyHTTPServer(s *http.Server, srv OntologyHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/ontology/entities", _Ontology_CreateEntityType0_HTTP_Handler(srv))
	r.POST("/v1/ontology/relations", _Ontology_CreateRelationType0_HTTP_Handler(srv))
	r.GET("/v1/ontology/entities", _Ontology_ListEntityTypes0_HTTP_Handler(srv))
	r.GET("/v1/ontology/relations", _Ontology_ListRelationTypes0_HTTP_Handler(srv))
}

func _Ontology_CreateEntityType0_HTTP_Handler(srv OntologyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEntityTypeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOntologyCreateEntityType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEntityType(ctx, req.(*CreateEntityTypeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEntityTypeReply)
		return ctx.Result(200, reply)
	}
}

func _Ontology_CreateRelationType0_HTTP_Handler(srv OntologyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRelationTypeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOntologyCreateRelationType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRelationType(ctx, req.(*CreateRelationTypeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRelationTypeReply)
		return ctx.Result(200, reply)
	}
}

func _Ontology_ListEntityTypes0_HTTP_Handler(srv OntologyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEntityTypesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOntologyListEntityTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEntityTypes(ctx, req.(*ListEntityTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEntityTypesReply)
		return ctx.Result(200, reply)
	}
}

func _Ontology_ListRelationTypes0_HTTP_Handler(srv OntologyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRelationTypesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOntologyListRelationTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRelationTypes(ctx, req.(*ListRelationTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRelationTypesReply)
		return ctx.Result(200, reply)
	}
}

type OntologyHTTPClient interface {
	// CreateEntityType Define a new EntityType in the Knowledge Graph
	CreateEntityType(ctx context.Context, req *CreateEntityTypeRequest, opts ...http.CallOption) (rsp *CreateEntityTypeReply, err error)
	// CreateRelationType Define a new RelationType in the Knowledge Graph
	CreateRelationType(ctx context.Context, req *CreateRelationTypeRequest, opts ...http.CallOption) (rsp *CreateRelationTypeReply, err error)
	// ListEntityTypes Get schema definitions for EntityTypes
	ListEntityTypes(ctx context.Context, req *ListEntityTypesRequest, opts ...http.CallOption) (rsp *ListEntityTypesReply, err error)
	// ListRelationTypes Get schema definitions for RelationTypes
	ListRelationTypes(ctx context.Context, req *ListRelationTypesRequest, opts ...http.CallOption) (rsp *ListRelationTypesReply, err error)
}

type OntologyHTTPClientImpl struct {
	cc *http.Client
}

func NewOntologyHTTPClient(client *http.Client) OntologyHTTPClient {
	return &OntologyHTTPClientImpl{client}
}

// CreateEntityType Define a new EntityType in the Knowledge Graph
func (c *OntologyHTTPClientImpl) CreateEntityType(ctx context.Context, in *CreateEntityTypeRequest, opts ...http.CallOption) (*CreateEntityTypeReply, error) {
	var out CreateEntityTypeReply
	pattern := "/v1/ontology/entities"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOntologyCreateEntityType))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateRelationType Define a new RelationType in the Knowledge Graph
func (c *OntologyHTTPClientImpl) CreateRelationType(ctx context.Context, in *CreateRelationTypeRequest, opts ...http.CallOption) (*CreateRelationTypeReply, error) {
	var out CreateRelationTypeReply
	pattern := "/v1/ontology/relations"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOntologyCreateRelationType))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEntityTypes Get schema definitions for EntityTypes
func (c *OntologyHTTPClientImpl) ListEntityTypes(ctx context.Context, in *ListEntityTypesRequest, opts ...http.CallOption) (*ListEntityTypesReply, error) {
	var out ListEntityTypesReply
	pattern := "/v1/ontology/entities"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOntologyListEntityTypes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRelationTypes Get schema definitions for RelationTypes
func (c *OntologyHTTPClientImpl) ListRelationTypes(ctx context.Context, in *ListRelationTypesRequest, opts ...http.CallOption) (*ListRelationTypesReply, error) {
	var out ListRelationTypesReply
	pattern := "/v1/ontology/relations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOntologyListRelationTypes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
