// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	"github.com/vnp-community/vnp-memory/services/memobase-context/internal/adapter/external"
	"github.com/vnp-community/vnp-memory/services/memobase-context/internal/adapter/grpc"
	"github.com/vnp-community/vnp-memory/services/memobase-context/internal/adapter/repository/postgres"
	"github.com/vnp-community/vnp-memory/services/memobase-context/internal/adapter/repository/redis"
	"github.com/vnp-community/vnp-memory/services/memobase-context/internal/usecase"
)

// Injectors from wire.go:

func InitializeHandler(pool *pgxpool.Pool, redisClient *redis.Client, cacheTTL int, defaultMaxTokenSize int32, profileEventRatio float32, eventThreshold float32, eventWindowDays int, eventTopK int) *grpc.Handler {
	profileCache := redis.NewProfileCache(redisClient)
	profileReadRepository := postgres.NewProfileReadRepository(pool)
	eventGistSearchRepository := postgres.NewEventGistSearchRepository(pool)
	
	profileFetcher := usecase.NewGetProfilesUseCase(profileReadRepository, profileCache, cacheTTL)
	
	contextAssembler := usecase.NewGetContextUseCase(
		profileFetcher, 
		eventGistSearchRepository, 
		defaultMaxTokenSize, 
		profileEventRatio, 
		eventThreshold, 
		eventWindowDays, 
		eventTopK,
	)
	
	embedder := external.NewDummyEmbedder()
	profileSearcher := usecase.NewSearchProfilesUseCase(profileReadRepository, embedder)
	
	handler := grpc.NewHandler(contextAssembler, profileFetcher, profileSearcher)
	return handler
}
