package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/vnp-community/vnp-memory/services/graphiti-ingestion/internal/infra/config"
	"github.com/vnp-community/vnp-memory/services/graphiti-ingestion/internal/infra/server"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/trace"
	"go.uber.org/zap"
)

func initTracer() (*trace.TracerProvider, error) {
	tp := trace.NewTracerProvider()
	otel.SetTracerProvider(tp)
	return tp, nil
}

func main() {
	logger, _ := zap.NewProduction()
	zap.ReplaceGlobals(logger)
	defer logger.Sync()

	tp, err := initTracer()
	if err != nil {
		zap.L().Fatal("Failed to initialize tracer", zap.Error(err))
	}
	defer func() {
		if err := tp.Shutdown(context.Background()); err != nil {
			zap.L().Error("Error shutting down tracer", zap.Error(err))
		}
	}()

	cfg, err := config.LoadConfig()
	if err != nil {
		zap.L().Fatal("Failed to load config", zap.Error(err))
	}

	// Start Prometheus Metrics server
	go func() {
		http.Handle("/metrics", promhttp.Handler())
		http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
			w.Write([]byte("OK"))
		})
		zap.L().Info("Starting metrics server", zap.Int("port", cfg.HealthPort))
		if err := http.ListenAndServe(":"+string(rune(cfg.HealthPort)), nil); err != nil {
			zap.L().Error("Metrics server failed", zap.Error(err))
		}
	}()

	// This would normally be generated by wire
	srv := server.NewGRPCServer(cfg.Port)

	// Saga Worker
	// In an actual wire injection, App struct would contain Server and Worker
	// worker := usecase.NewSagaWorker(repo, orch, 1*time.Minute)
	// worker.Start()
	// defer worker.Stop()

	go func() {
		zap.L().Info("Starting gRPC server", zap.Int("port", cfg.Port))
		if err := srv.Start(); err != nil {
			zap.L().Fatal("Server error", zap.Error(err))
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	zap.L().Info("Gracefully stopping server...")
	
	// Create context with timeout for graceful shutdown
	_, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	
	// Stop worker to prevent new sagas
	// worker.Stop()
	
	// Wait for ongoing gRPC requests to finish
	srv.Stop()
	
	zap.L().Info("Server stopped gracefully")
}
