// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: graphiti.proto

package graphitiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphitiIngestionService_IngestEpisode_FullMethodName = "/vnp.gateway.graphiti.v1.GraphitiIngestionService/IngestEpisode"
)

// GraphitiIngestionServiceClient is the client API for GraphitiIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphitiIngestionService handles episode and entity ingestion.
type GraphitiIngestionServiceClient interface {
	IngestEpisode(ctx context.Context, in *IngestEpisodeRequest, opts ...grpc.CallOption) (*IngestEpisodeResponse, error)
}

type graphitiIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphitiIngestionServiceClient(cc grpc.ClientConnInterface) GraphitiIngestionServiceClient {
	return &graphitiIngestionServiceClient{cc}
}

func (c *graphitiIngestionServiceClient) IngestEpisode(ctx context.Context, in *IngestEpisodeRequest, opts ...grpc.CallOption) (*IngestEpisodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEpisodeResponse)
	err := c.cc.Invoke(ctx, GraphitiIngestionService_IngestEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphitiIngestionServiceServer is the server API for GraphitiIngestionService service.
// All implementations must embed UnimplementedGraphitiIngestionServiceServer
// for forward compatibility.
//
// GraphitiIngestionService handles episode and entity ingestion.
type GraphitiIngestionServiceServer interface {
	IngestEpisode(context.Context, *IngestEpisodeRequest) (*IngestEpisodeResponse, error)
	mustEmbedUnimplementedGraphitiIngestionServiceServer()
}

// UnimplementedGraphitiIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphitiIngestionServiceServer struct{}

func (UnimplementedGraphitiIngestionServiceServer) IngestEpisode(context.Context, *IngestEpisodeRequest) (*IngestEpisodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestEpisode not implemented")
}
func (UnimplementedGraphitiIngestionServiceServer) mustEmbedUnimplementedGraphitiIngestionServiceServer() {
}
func (UnimplementedGraphitiIngestionServiceServer) testEmbeddedByValue() {}

// UnsafeGraphitiIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphitiIngestionServiceServer will
// result in compilation errors.
type UnsafeGraphitiIngestionServiceServer interface {
	mustEmbedUnimplementedGraphitiIngestionServiceServer()
}

func RegisterGraphitiIngestionServiceServer(s grpc.ServiceRegistrar, srv GraphitiIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphitiIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphitiIngestionService_ServiceDesc, srv)
}

func _GraphitiIngestionService_IngestEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphitiIngestionServiceServer).IngestEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphitiIngestionService_IngestEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphitiIngestionServiceServer).IngestEpisode(ctx, req.(*IngestEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphitiIngestionService_ServiceDesc is the grpc.ServiceDesc for GraphitiIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphitiIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vnp.gateway.graphiti.v1.GraphitiIngestionService",
	HandlerType: (*GraphitiIngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestEpisode",
			Handler:    _GraphitiIngestionService_IngestEpisode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graphiti.proto",
}

const (
	GraphitiSearchService_Search_FullMethodName = "/vnp.gateway.graphiti.v1.GraphitiSearchService/Search"
)

// GraphitiSearchServiceClient is the client API for GraphitiSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphitiSearchService handles graph search queries.
type GraphitiSearchServiceClient interface {
	Search(ctx context.Context, in *GraphSearchRequest, opts ...grpc.CallOption) (*GraphSearchResponse, error)
}

type graphitiSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphitiSearchServiceClient(cc grpc.ClientConnInterface) GraphitiSearchServiceClient {
	return &graphitiSearchServiceClient{cc}
}

func (c *graphitiSearchServiceClient) Search(ctx context.Context, in *GraphSearchRequest, opts ...grpc.CallOption) (*GraphSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphSearchResponse)
	err := c.cc.Invoke(ctx, GraphitiSearchService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphitiSearchServiceServer is the server API for GraphitiSearchService service.
// All implementations must embed UnimplementedGraphitiSearchServiceServer
// for forward compatibility.
//
// GraphitiSearchService handles graph search queries.
type GraphitiSearchServiceServer interface {
	Search(context.Context, *GraphSearchRequest) (*GraphSearchResponse, error)
	mustEmbedUnimplementedGraphitiSearchServiceServer()
}

// UnimplementedGraphitiSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphitiSearchServiceServer struct{}

func (UnimplementedGraphitiSearchServiceServer) Search(context.Context, *GraphSearchRequest) (*GraphSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGraphitiSearchServiceServer) mustEmbedUnimplementedGraphitiSearchServiceServer() {}
func (UnimplementedGraphitiSearchServiceServer) testEmbeddedByValue()                               {}

// UnsafeGraphitiSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphitiSearchServiceServer will
// result in compilation errors.
type UnsafeGraphitiSearchServiceServer interface {
	mustEmbedUnimplementedGraphitiSearchServiceServer()
}

func RegisterGraphitiSearchServiceServer(s grpc.ServiceRegistrar, srv GraphitiSearchServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphitiSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphitiSearchService_ServiceDesc, srv)
}

func _GraphitiSearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphitiSearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphitiSearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphitiSearchServiceServer).Search(ctx, req.(*GraphSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphitiSearchService_ServiceDesc is the grpc.ServiceDesc for GraphitiSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphitiSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vnp.gateway.graphiti.v1.GraphitiSearchService",
	HandlerType: (*GraphitiSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _GraphitiSearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graphiti.proto",
}

const (
	GraphitiStoreService_GetNode_FullMethodName = "/vnp.gateway.graphiti.v1.GraphitiStoreService/GetNode"
	GraphitiStoreService_GetEdge_FullMethodName = "/vnp.gateway.graphiti.v1.GraphitiStoreService/GetEdge"
)

// GraphitiStoreServiceClient is the client API for GraphitiStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphitiStoreService provides direct node/edge access.
type GraphitiStoreServiceClient interface {
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error)
	GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*Edge, error)
}

type graphitiStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphitiStoreServiceClient(cc grpc.ClientConnInterface) GraphitiStoreServiceClient {
	return &graphitiStoreServiceClient{cc}
}

func (c *graphitiStoreServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, GraphitiStoreService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphitiStoreServiceClient) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*Edge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Edge)
	err := c.cc.Invoke(ctx, GraphitiStoreService_GetEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphitiStoreServiceServer is the server API for GraphitiStoreService service.
// All implementations must embed UnimplementedGraphitiStoreServiceServer
// for forward compatibility.
//
// GraphitiStoreService provides direct node/edge access.
type GraphitiStoreServiceServer interface {
	GetNode(context.Context, *GetNodeRequest) (*Node, error)
	GetEdge(context.Context, *GetEdgeRequest) (*Edge, error)
	mustEmbedUnimplementedGraphitiStoreServiceServer()
}

// UnimplementedGraphitiStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphitiStoreServiceServer struct{}

func (UnimplementedGraphitiStoreServiceServer) GetNode(context.Context, *GetNodeRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedGraphitiStoreServiceServer) GetEdge(context.Context, *GetEdgeRequest) (*Edge, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdge not implemented")
}
func (UnimplementedGraphitiStoreServiceServer) mustEmbedUnimplementedGraphitiStoreServiceServer() {}
func (UnimplementedGraphitiStoreServiceServer) testEmbeddedByValue()                              {}

// UnsafeGraphitiStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphitiStoreServiceServer will
// result in compilation errors.
type UnsafeGraphitiStoreServiceServer interface {
	mustEmbedUnimplementedGraphitiStoreServiceServer()
}

func RegisterGraphitiStoreServiceServer(s grpc.ServiceRegistrar, srv GraphitiStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphitiStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphitiStoreService_ServiceDesc, srv)
}

func _GraphitiStoreService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphitiStoreServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphitiStoreService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphitiStoreServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphitiStoreService_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphitiStoreServiceServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphitiStoreService_GetEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphitiStoreServiceServer).GetEdge(ctx, req.(*GetEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphitiStoreService_ServiceDesc is the grpc.ServiceDesc for GraphitiStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphitiStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vnp.gateway.graphiti.v1.GraphitiStoreService",
	HandlerType: (*GraphitiStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNode",
			Handler:    _GraphitiStoreService_GetNode_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _GraphitiStoreService_GetEdge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graphiti.proto",
}
