package grpc

import (
	"context"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/vnp-community/vnp-memory/services/cognee-cognify/internal/usecase/dto"
	"github.com/vnp-community/vnp-memory/services/cognee-cognify/internal/usecase/port"
)

// In a real application, these would be generated by protoc.
type TriggerCognifyRequest struct {
	DatasetId string
	TenantId  string
}

type GetJobStatusRequest struct {
	JobId    string
	TenantId string
}

type CognifyJob struct {
	Id     string
	Status string
	Stage  string
}

// CogneeCognifyServiceServer interface represents the generated gRPC server.
type CogneeCognifyServiceServer interface {
	TriggerCognify(context.Context, *TriggerCognifyRequest) (*CognifyJob, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*CognifyJob, error)
}

type handler struct {
	cognifyUseCase port.CognifyUseCase
	jobManager     port.JobManager
}

func NewHandler(uc port.CognifyUseCase, jm port.JobManager) CogneeCognifyServiceServer {
	return &handler{
		cognifyUseCase: uc,
		jobManager:     jm,
	}
}

func (h *handler) TriggerCognify(ctx context.Context, req *TriggerCognifyRequest) (*CognifyJob, error) {
	datasetID, err := uuid.Parse(req.DatasetId)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid dataset_id")
	}

	res, err := h.cognifyUseCase.Execute(ctx, dto.TriggerCognifyReq{
		DatasetID: datasetID,
		TenantID:  req.TenantId,
	})
	if err != nil {
		return nil, status.Errorf(codes.Internal, "pipeline error: %v", err)
	}

	return &CognifyJob{
		Id:     res.JobID.String(),
		Status: string(res.Status),
		Stage:  string(res.Stage),
	}, nil
}

func (h *handler) GetJobStatus(ctx context.Context, req *GetJobStatusRequest) (*CognifyJob, error) {
	jobID, err := uuid.Parse(req.JobId)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid job_id")
	}

	job, err := h.jobManager.GetJobStatus(ctx, req.TenantId, jobID)
	if err != nil {
		return nil, status.Errorf(codes.NotFound, "job not found: %v", err)
	}

	return &CognifyJob{
		Id:     job.ID.String(),
		Status: string(job.Status),
		Stage:  string(job.Stage),
	}, nil
}
