// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/client/llm_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapter/client/llm_client.go -destination=internal/mocks/llm_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/vnp-memory/services/ov-session/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// CompressSession mocks base method.
func (m *MockLLMClient) CompressSession(ctx context.Context, messages []*model.Message, version model.CompressionVersion) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressSession", ctx, messages, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompressSession indicates an expected call of CompressSession.
func (mr *MockLLMClientMockRecorder) CompressSession(ctx, messages, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressSession", reflect.TypeOf((*MockLLMClient)(nil).CompressSession), ctx, messages, version)
}

// EvaluateWM mocks base method.
func (m *MockLLMClient) EvaluateWM(ctx context.Context, currentWM *model.WorkingMemory, newMsg *model.Message) (*model.WorkingMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateWM", ctx, currentWM, newMsg)
	ret0, _ := ret[0].(*model.WorkingMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateWM indicates an expected call of EvaluateWM.
func (mr *MockLLMClientMockRecorder) EvaluateWM(ctx, currentWM, newMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateWM", reflect.TypeOf((*MockLLMClient)(nil).EvaluateWM), ctx, currentWM, newMsg)
}

// ExtractMemories mocks base method.
func (m *MockLLMClient) ExtractMemories(ctx context.Context, archive string) ([]model.CandidateMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractMemories", ctx, archive)
	ret0, _ := ret[0].([]model.CandidateMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractMemories indicates an expected call of ExtractMemories.
func (mr *MockLLMClientMockRecorder) ExtractMemories(ctx, archive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractMemories", reflect.TypeOf((*MockLLMClient)(nil).ExtractMemories), ctx, archive)
}

// FuseMemories mocks base method.
func (m *MockLLMClient) FuseMemories(ctx context.Context, m1, m2 *model.CandidateMemory) (*model.CandidateMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FuseMemories", ctx, m1, m2)
	ret0, _ := ret[0].(*model.CandidateMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FuseMemories indicates an expected call of FuseMemories.
func (mr *MockLLMClientMockRecorder) FuseMemories(ctx, m1, m2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FuseMemories", reflect.TypeOf((*MockLLMClient)(nil).FuseMemories), ctx, m1, m2)
}
