run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - bodyclose
    - unconvert
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
