// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/port/input.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/port/input.go -destination=internal/usecase/port/mock/input_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "vnp-memory/services/cognee-ingestion/internal/domain"
	dto "vnp-memory/services/cognee-ingestion/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockFileIngester is a mock of FileIngester interface.
type MockFileIngester struct {
	ctrl     *gomock.Controller
	recorder *MockFileIngesterMockRecorder
	isgomock struct{}
}

// MockFileIngesterMockRecorder is the mock recorder for MockFileIngester.
type MockFileIngesterMockRecorder struct {
	mock *MockFileIngester
}

// NewMockFileIngester creates a new mock instance.
func NewMockFileIngester(ctrl *gomock.Controller) *MockFileIngester {
	mock := &MockFileIngester{ctrl: ctrl}
	mock.recorder = &MockFileIngesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileIngester) EXPECT() *MockFileIngesterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFileIngester) Execute(ctx context.Context, req dto.IngestFileRequest) (*dto.IngestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*dto.IngestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFileIngesterMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFileIngester)(nil).Execute), ctx, req)
}

// MockTextIngester is a mock of TextIngester interface.
type MockTextIngester struct {
	ctrl     *gomock.Controller
	recorder *MockTextIngesterMockRecorder
	isgomock struct{}
}

// MockTextIngesterMockRecorder is the mock recorder for MockTextIngester.
type MockTextIngesterMockRecorder struct {
	mock *MockTextIngester
}

// NewMockTextIngester creates a new mock instance.
func NewMockTextIngester(ctrl *gomock.Controller) *MockTextIngester {
	mock := &MockTextIngester{ctrl: ctrl}
	mock.recorder = &MockTextIngesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextIngester) EXPECT() *MockTextIngesterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTextIngester) Execute(ctx context.Context, req dto.IngestTextRequest) (*dto.IngestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*dto.IngestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTextIngesterMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTextIngester)(nil).Execute), ctx, req)
}

// MockURLIngester is a mock of URLIngester interface.
type MockURLIngester struct {
	ctrl     *gomock.Controller
	recorder *MockURLIngesterMockRecorder
	isgomock struct{}
}

// MockURLIngesterMockRecorder is the mock recorder for MockURLIngester.
type MockURLIngesterMockRecorder struct {
	mock *MockURLIngester
}

// NewMockURLIngester creates a new mock instance.
func NewMockURLIngester(ctrl *gomock.Controller) *MockURLIngester {
	mock := &MockURLIngester{ctrl: ctrl}
	mock.recorder = &MockURLIngesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLIngester) EXPECT() *MockURLIngesterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockURLIngester) Execute(ctx context.Context, req dto.IngestURLRequest) (*dto.IngestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*dto.IngestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockURLIngesterMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockURLIngester)(nil).Execute), ctx, req)
}

// MockDatasetManager is a mock of DatasetManager interface.
type MockDatasetManager struct {
	ctrl     *gomock.Controller
	recorder *MockDatasetManagerMockRecorder
	isgomock struct{}
}

// MockDatasetManagerMockRecorder is the mock recorder for MockDatasetManager.
type MockDatasetManagerMockRecorder struct {
	mock *MockDatasetManager
}

// NewMockDatasetManager creates a new mock instance.
func NewMockDatasetManager(ctrl *gomock.Controller) *MockDatasetManager {
	mock := &MockDatasetManager{ctrl: ctrl}
	mock.recorder = &MockDatasetManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatasetManager) EXPECT() *MockDatasetManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDatasetManager) Create(ctx context.Context, tenantID, name, description string) (*domain.Dataset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenantID, name, description)
	ret0, _ := ret[0].(*domain.Dataset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDatasetManagerMockRecorder) Create(ctx, tenantID, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDatasetManager)(nil).Create), ctx, tenantID, name, description)
}

// Delete mocks base method.
func (m *MockDatasetManager) Delete(ctx context.Context, tenantID string, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDatasetManagerMockRecorder) Delete(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatasetManager)(nil).Delete), ctx, tenantID, id)
}

// Get mocks base method.
func (m *MockDatasetManager) Get(ctx context.Context, tenantID string, id uuid.UUID) (*domain.Dataset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantID, id)
	ret0, _ := ret[0].(*domain.Dataset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDatasetManagerMockRecorder) Get(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatasetManager)(nil).Get), ctx, tenantID, id)
}

// GetStatus mocks base method.
func (m *MockDatasetManager) GetStatus(ctx context.Context, tenantID string, id uuid.UUID) (*dto.DatasetStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, tenantID, id)
	ret0, _ := ret[0].(*dto.DatasetStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockDatasetManagerMockRecorder) GetStatus(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockDatasetManager)(nil).GetStatus), ctx, tenantID, id)
}

// List mocks base method.
func (m *MockDatasetManager) List(ctx context.Context, tenantID, cursor string, limit int) ([]*domain.Dataset, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, cursor, limit)
	ret0, _ := ret[0].([]*domain.Dataset)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDatasetManagerMockRecorder) List(ctx, tenantID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDatasetManager)(nil).List), ctx, tenantID, cursor, limit)
}
