// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: accesscontrol/v1/policy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RegoContent   string                 `protobuf:"bytes,3,opt,name=rego_content,json=regoContent,proto3" json:"rego_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_accesscontrol_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePolicyRequest) GetRegoContent() string {
	if x != nil {
		return x.RegoContent
	}
	return ""
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_accesscontrol_v1_policy_proto_rawDescGZIP(), []int{1}
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_accesscontrol_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *GetPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PolicyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RegoContent   string                 `protobuf:"bytes,4,opt,name=rego_content,json=regoContent,proto3" json:"rego_content,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyReply) Reset() {
	*x = PolicyReply{}
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyReply) ProtoMessage() {}

func (x *PolicyReply) ProtoReflect() protoreflect.Message {
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyReply.ProtoReflect.Descriptor instead.
func (*PolicyReply) Descriptor() ([]byte, []int) {
	return file_accesscontrol_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PolicyReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicyReply) GetRegoContent() string {
	if x != nil {
		return x.RegoContent
	}
	return ""
}

func (x *PolicyReply) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListPoliciesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyReply         `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesReply) Reset() {
	*x = ListPoliciesReply{}
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesReply) ProtoMessage() {}

func (x *ListPoliciesReply) ProtoReflect() protoreflect.Message {
	mi := &file_accesscontrol_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesReply.ProtoReflect.Descriptor instead.
func (*ListPoliciesReply) Descriptor() ([]byte, []int) {
	return file_accesscontrol_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *ListPoliciesReply) GetPolicies() []*PolicyReply {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_accesscontrol_v1_policy_proto protoreflect.FileDescriptor

const file_accesscontrol_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1daccesscontrol/v1/policy.proto\x12\x14api.accesscontrol.v1\x1a\x1cgoogle/api/annotations.proto\"n\n" +
	"\x13CreatePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\frego_content\x18\x03 \x01(\tR\vregoContent\"\x15\n" +
	"\x13ListPoliciesRequest\"\"\n" +
	"\x10GetPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x93\x01\n" +
	"\vPolicyReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\frego_content\x18\x04 \x01(\tR\vregoContent\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"R\n" +
	"\x11ListPoliciesReply\x12=\n" +
	"\bpolicies\x18\x01 \x03(\v2!.api.accesscontrol.v1.PolicyReplyR\bpolicies2\xf3\x02\n" +
	"\rAccessControl\x12u\n" +
	"\fCreatePolicy\x12).api.accesscontrol.v1.CreatePolicyRequest\x1a!.api.accesscontrol.v1.PolicyReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/policies\x12x\n" +
	"\fListPolicies\x12).api.accesscontrol.v1.ListPoliciesRequest\x1a'.api.accesscontrol.v1.ListPoliciesReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/policies\x12q\n" +
	"\tGetPolicy\x12&.api.accesscontrol.v1.GetPolicyRequest\x1a!.api.accesscontrol.v1.PolicyReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/policies/{id}B&Z$kgs-platform/api/accesscontrol/v1;v1b\x06proto3"

var (
	file_accesscontrol_v1_policy_proto_rawDescOnce sync.Once
	file_accesscontrol_v1_policy_proto_rawDescData []byte
)

func file_accesscontrol_v1_policy_proto_rawDescGZIP() []byte {
	file_accesscontrol_v1_policy_proto_rawDescOnce.Do(func() {
		file_accesscontrol_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accesscontrol_v1_policy_proto_rawDesc), len(file_accesscontrol_v1_policy_proto_rawDesc)))
	})
	return file_accesscontrol_v1_policy_proto_rawDescData
}

var file_accesscontrol_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_accesscontrol_v1_policy_proto_goTypes = []any{
	(*CreatePolicyRequest)(nil), // 0: api.accesscontrol.v1.CreatePolicyRequest
	(*ListPoliciesRequest)(nil), // 1: api.accesscontrol.v1.ListPoliciesRequest
	(*GetPolicyRequest)(nil),    // 2: api.accesscontrol.v1.GetPolicyRequest
	(*PolicyReply)(nil),         // 3: api.accesscontrol.v1.PolicyReply
	(*ListPoliciesReply)(nil),   // 4: api.accesscontrol.v1.ListPoliciesReply
}
var file_accesscontrol_v1_policy_proto_depIdxs = []int32{
	3, // 0: api.accesscontrol.v1.ListPoliciesReply.policies:type_name -> api.accesscontrol.v1.PolicyReply
	0, // 1: api.accesscontrol.v1.AccessControl.CreatePolicy:input_type -> api.accesscontrol.v1.CreatePolicyRequest
	1, // 2: api.accesscontrol.v1.AccessControl.ListPolicies:input_type -> api.accesscontrol.v1.ListPoliciesRequest
	2, // 3: api.accesscontrol.v1.AccessControl.GetPolicy:input_type -> api.accesscontrol.v1.GetPolicyRequest
	3, // 4: api.accesscontrol.v1.AccessControl.CreatePolicy:output_type -> api.accesscontrol.v1.PolicyReply
	4, // 5: api.accesscontrol.v1.AccessControl.ListPolicies:output_type -> api.accesscontrol.v1.ListPoliciesReply
	3, // 6: api.accesscontrol.v1.AccessControl.GetPolicy:output_type -> api.accesscontrol.v1.PolicyReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accesscontrol_v1_policy_proto_init() }
func file_accesscontrol_v1_policy_proto_init() {
	if File_accesscontrol_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accesscontrol_v1_policy_proto_rawDesc), len(file_accesscontrol_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accesscontrol_v1_policy_proto_goTypes,
		DependencyIndexes: file_accesscontrol_v1_policy_proto_depIdxs,
		MessageInfos:      file_accesscontrol_v1_policy_proto_msgTypes,
	}.Build()
	File_accesscontrol_v1_policy_proto = out.File
	file_accesscontrol_v1_policy_proto_goTypes = nil
	file_accesscontrol_v1_policy_proto_depIdxs = nil
}
