// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: ontology/v1/ontology.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ontology_CreateEntityType_FullMethodName   = "/api.ontology.v1.Ontology/CreateEntityType"
	Ontology_CreateRelationType_FullMethodName = "/api.ontology.v1.Ontology/CreateRelationType"
	Ontology_ListEntityTypes_FullMethodName    = "/api.ontology.v1.Ontology/ListEntityTypes"
	Ontology_ListRelationTypes_FullMethodName  = "/api.ontology.v1.Ontology/ListRelationTypes"
)

// OntologyClient is the client API for Ontology service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OntologyClient interface {
	// Define a new EntityType in the Knowledge Graph
	CreateEntityType(ctx context.Context, in *CreateEntityTypeRequest, opts ...grpc.CallOption) (*CreateEntityTypeReply, error)
	// Define a new RelationType in the Knowledge Graph
	CreateRelationType(ctx context.Context, in *CreateRelationTypeRequest, opts ...grpc.CallOption) (*CreateRelationTypeReply, error)
	// Get schema definitions for EntityTypes
	ListEntityTypes(ctx context.Context, in *ListEntityTypesRequest, opts ...grpc.CallOption) (*ListEntityTypesReply, error)
	// Get schema definitions for RelationTypes
	ListRelationTypes(ctx context.Context, in *ListRelationTypesRequest, opts ...grpc.CallOption) (*ListRelationTypesReply, error)
}

type ontologyClient struct {
	cc grpc.ClientConnInterface
}

func NewOntologyClient(cc grpc.ClientConnInterface) OntologyClient {
	return &ontologyClient{cc}
}

func (c *ontologyClient) CreateEntityType(ctx context.Context, in *CreateEntityTypeRequest, opts ...grpc.CallOption) (*CreateEntityTypeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEntityTypeReply)
	err := c.cc.Invoke(ctx, Ontology_CreateEntityType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) CreateRelationType(ctx context.Context, in *CreateRelationTypeRequest, opts ...grpc.CallOption) (*CreateRelationTypeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRelationTypeReply)
	err := c.cc.Invoke(ctx, Ontology_CreateRelationType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) ListEntityTypes(ctx context.Context, in *ListEntityTypesRequest, opts ...grpc.CallOption) (*ListEntityTypesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntityTypesReply)
	err := c.cc.Invoke(ctx, Ontology_ListEntityTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyClient) ListRelationTypes(ctx context.Context, in *ListRelationTypesRequest, opts ...grpc.CallOption) (*ListRelationTypesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRelationTypesReply)
	err := c.cc.Invoke(ctx, Ontology_ListRelationTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OntologyServer is the server API for Ontology service.
// All implementations must embed UnimplementedOntologyServer
// for forward compatibility.
type OntologyServer interface {
	// Define a new EntityType in the Knowledge Graph
	CreateEntityType(context.Context, *CreateEntityTypeRequest) (*CreateEntityTypeReply, error)
	// Define a new RelationType in the Knowledge Graph
	CreateRelationType(context.Context, *CreateRelationTypeRequest) (*CreateRelationTypeReply, error)
	// Get schema definitions for EntityTypes
	ListEntityTypes(context.Context, *ListEntityTypesRequest) (*ListEntityTypesReply, error)
	// Get schema definitions for RelationTypes
	ListRelationTypes(context.Context, *ListRelationTypesRequest) (*ListRelationTypesReply, error)
	mustEmbedUnimplementedOntologyServer()
}

// UnimplementedOntologyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOntologyServer struct{}

func (UnimplementedOntologyServer) CreateEntityType(context.Context, *CreateEntityTypeRequest) (*CreateEntityTypeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEntityType not implemented")
}
func (UnimplementedOntologyServer) CreateRelationType(context.Context, *CreateRelationTypeRequest) (*CreateRelationTypeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRelationType not implemented")
}
func (UnimplementedOntologyServer) ListEntityTypes(context.Context, *ListEntityTypesRequest) (*ListEntityTypesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntityTypes not implemented")
}
func (UnimplementedOntologyServer) ListRelationTypes(context.Context, *ListRelationTypesRequest) (*ListRelationTypesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRelationTypes not implemented")
}
func (UnimplementedOntologyServer) mustEmbedUnimplementedOntologyServer() {}
func (UnimplementedOntologyServer) testEmbeddedByValue()                  {}

// UnsafeOntologyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OntologyServer will
// result in compilation errors.
type UnsafeOntologyServer interface {
	mustEmbedUnimplementedOntologyServer()
}

func RegisterOntologyServer(s grpc.ServiceRegistrar, srv OntologyServer) {
	// If the following call panics, it indicates UnimplementedOntologyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ontology_ServiceDesc, srv)
}

func _Ontology_CreateEntityType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).CreateEntityType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ontology_CreateEntityType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).CreateEntityType(ctx, req.(*CreateEntityTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_CreateRelationType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRelationTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).CreateRelationType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ontology_CreateRelationType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).CreateRelationType(ctx, req.(*CreateRelationTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_ListEntityTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntityTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).ListEntityTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ontology_ListEntityTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).ListEntityTypes(ctx, req.(*ListEntityTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ontology_ListRelationTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRelationTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyServer).ListRelationTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ontology_ListRelationTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyServer).ListRelationTypes(ctx, req.(*ListRelationTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ontology_ServiceDesc is the grpc.ServiceDesc for Ontology service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ontology_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ontology.v1.Ontology",
	HandlerType: (*OntologyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntityType",
			Handler:    _Ontology_CreateEntityType_Handler,
		},
		{
			MethodName: "CreateRelationType",
			Handler:    _Ontology_CreateRelationType_Handler,
		},
		{
			MethodName: "ListEntityTypes",
			Handler:    _Ontology_ListEntityTypes_Handler,
		},
		{
			MethodName: "ListRelationTypes",
			Handler:    _Ontology_ListRelationTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ontology/v1/ontology.proto",
}
