package surrealdb

import (
	"fmt"
	"regexp"
	"strings"
)

// TranslateCypherToSurrealQL converts a Cypher query (generated by QueryPlanner)
// into an equivalent SurrealQL query.
//
// This is NOT a general-purpose Cypher parser. It handles only the ~5 patterns
// that QueryPlanner.Build*() methods generate.
func TranslateCypherToSurrealQL(cypher string, params map[string]any) (string, error) {
	normalized := strings.TrimSpace(cypher)

	// Pattern 1: Context query — neighborhood traversal
	// MATCH (n {app_id: $app_id, tenant_id: $tenant_id})-[r]-(m) WHERE n.id = $node_id
	if isContextQuery(normalized) {
		return buildContextSurrealQL(params), nil
	}

	// Pattern 2: Impact query — downstream traversal with depth
	// MATCH p=(n)-[*1..N]->(m) WHERE n.app_id = $app_id ...
	if depth, ok := extractImpactDepth(normalized); ok {
		return buildImpactSurrealQL(params, depth), nil
	}

	// Pattern 3: Coverage query — upstream traversal with depth
	// MATCH p=(n)<-[*1..N]-(m) WHERE n.app_id = $app_id ...
	if depth, ok := extractCoverageDepth(normalized); ok {
		return buildCoverageSurrealQL(params, depth), nil
	}

	// Pattern 4: Subgraph query — nodes by ID list
	// MATCH (n)-[r]->(m) WHERE n.id IN $node_ids
	if isSubgraphQuery(normalized) {
		return buildSubgraphSurrealQL(params), nil
	}

	// Pattern 5: Simple node lookup
	if isSimpleNodeLookup(normalized) {
		return buildSimpleLookupSurrealQL(params), nil
	}

	return "", fmt.Errorf("unsupported cypher pattern: %s", truncate(normalized, 200))
}

// ── Pattern Detectors ─────────────────────────────────────────

var (
	contextPattern  = regexp.MustCompile(`(?i)MATCH\s+\(.*\)\s*-\[.*\]-\s*\(`)
	impactPattern   = regexp.MustCompile(`(?i)\[\*1\.\.(\d+)\]\s*->\s*\(`)
	coveragePattern = regexp.MustCompile(`(?i)<-\s*\[\*1\.\.(\d+)\]\s*-\s*\(`)
	subgraphPattern = regexp.MustCompile(`(?i)IN\s+\$node_ids`)
	simpleLookup    = regexp.MustCompile(`(?i)MATCH\s+\(n\s*\{.*\}\)\s+RETURN`)
)

func isContextQuery(cypher string) bool {
	return contextPattern.MatchString(cypher) && !impactPattern.MatchString(cypher) && !coveragePattern.MatchString(cypher)
}

func extractImpactDepth(cypher string) (int, bool) {
	matches := impactPattern.FindStringSubmatch(cypher)
	if len(matches) < 2 {
		return 0, false
	}
	var depth int
	fmt.Sscanf(matches[1], "%d", &depth)
	return depth, true
}

func extractCoverageDepth(cypher string) (int, bool) {
	matches := coveragePattern.FindStringSubmatch(cypher)
	if len(matches) < 2 {
		return 0, false
	}
	var depth int
	fmt.Sscanf(matches[1], "%d", &depth)
	return depth, true
}

func isSubgraphQuery(cypher string) bool {
	return subgraphPattern.MatchString(cypher)
}

func isSimpleNodeLookup(cypher string) bool {
	return simpleLookup.MatchString(cypher)
}

// ── SurrealQL Builders ────────────────────────────────────────

func buildContextSurrealQL(params map[string]any) string {
	// Get the target node and its 1-hop neighbors (both directions)
	return `LET $target = (SELECT * FROM kg_entities WHERE entity_id = $node_id AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false LIMIT 1);
LET $outgoing = (SELECT * FROM kg_edges WHERE from_entity_id = $node_id AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false);
LET $incoming = (SELECT * FROM kg_edges WHERE to_entity_id = $node_id AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false);
LET $neighbor_ids = array::union(
  (SELECT VALUE to_entity_id FROM $outgoing),
  (SELECT VALUE from_entity_id FROM $incoming)
);
LET $neighbors = (SELECT * FROM kg_entities WHERE entity_id IN $neighbor_ids AND is_deleted = false);
RETURN { nodes: array::union($target, $neighbors), edges: array::union($outgoing, $incoming) };`
}

func buildImpactSurrealQL(params map[string]any, depth int) string {
	// Multi-hop downstream traversal via iterative edge following
	return fmt.Sprintf(`LET $visited = [$node_id];
LET $frontier = [$node_id];
LET $all_edges = [];
LET $depth = 0;

-- Iterative BFS up to depth %d
REPEAT {
  LET $new_edges = (SELECT * FROM kg_edges 
    WHERE from_entity_id IN $frontier AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false
    AND to_entity_id NOT IN $visited);
  LET $new_ids = (SELECT VALUE to_entity_id FROM $new_edges);
  LET $all_edges = array::union($all_edges, $new_edges);
  LET $visited = array::union($visited, $new_ids);
  LET $frontier = $new_ids;
  LET $depth = $depth + 1;
} WHILE $depth < %d AND array::len($frontier) > 0;

LET $nodes = (SELECT * FROM kg_entities WHERE entity_id IN $visited AND is_deleted = false);
RETURN { nodes: $nodes, edges: $all_edges };`, depth, depth)
}

func buildCoverageSurrealQL(params map[string]any, depth int) string {
	// Multi-hop upstream traversal (reverse direction)
	return fmt.Sprintf(`LET $visited = [$node_id];
LET $frontier = [$node_id];
LET $all_edges = [];
LET $depth = 0;

REPEAT {
  LET $new_edges = (SELECT * FROM kg_edges
    WHERE to_entity_id IN $frontier AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false
    AND from_entity_id NOT IN $visited);
  LET $new_ids = (SELECT VALUE from_entity_id FROM $new_edges);
  LET $all_edges = array::union($all_edges, $new_edges);
  LET $visited = array::union($visited, $new_ids);
  LET $frontier = $new_ids;
  LET $depth = $depth + 1;
} WHILE $depth < %d AND array::len($frontier) > 0;

LET $nodes = (SELECT * FROM kg_entities WHERE entity_id IN $visited AND is_deleted = false);
RETURN { nodes: $nodes, edges: $all_edges };`, depth, depth)
}

func buildSubgraphSurrealQL(params map[string]any) string {
	return `LET $nodes = (SELECT * FROM kg_entities
  WHERE entity_id IN $node_ids AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false);
LET $edges = (SELECT * FROM kg_edges
  WHERE from_entity_id IN $node_ids AND to_entity_id IN $node_ids
  AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false);
RETURN { nodes: $nodes, edges: $edges };`
}

func buildSimpleLookupSurrealQL(params map[string]any) string {
	return `SELECT * FROM kg_entities
  WHERE entity_id = $node_id AND app_id = $app_id AND tenant_id = $tenant_id AND is_deleted = false
  LIMIT 1;`
}
