// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"openviking.com/ov-resource/internal/adapter/grpc"
	"openviking.com/ov-resource/internal/infra/config"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config, db *sql.DB) (*grpc.Handler, error) {
	parserConfig := provideParserConfig(cfg)
	parserPort := provideParserRegistry(parserConfig)
	fileWriterPort := provideFileWriter(cfg)
	eventPublisherPort := provideEventPublisher(cfg)
	resourceRepository := provideResourceRepo(db)
	ingestUseCase := provideIngestUseCase(parserPort, fileWriterPort, eventPublisherPort, resourceRepository, cfg)
	parseUseCase := provideParseUseCase(parserPort)
	watchRepository := provideWatchRepo(db)
	watchUseCase := provideWatchUseCase(watchRepository, ingestUseCase, cfg)
	refreshUseCase := provideRefreshUseCase(ingestUseCase)
	handler := grpc.NewHandler(ingestUseCase, parseUseCase, watchUseCase, refreshUseCase)
	return handler, nil
}
