// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/cognee/search/v1/search.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Query       string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Strategies  []string               `protobuf:"bytes,2,rep,name=strategies,proto3" json:"strategies,omitempty"`
	DatasetId   string                 `protobuf:"bytes,3,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	DatasetName string                 `protobuf:"bytes,4,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	TenantId    string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NodeSets    []string               `protobuf:"bytes,6,rep,name=node_sets,json=nodeSets,proto3" json:"node_sets,omitempty"` // [NEW] CR-002
	TopK        int32                  `protobuf:"varint,7,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// [NEW] CR-005 Feedback fields
	SaveInteraction bool     `protobuf:"varint,8,opt,name=save_interaction,json=saveInteraction,proto3" json:"save_interaction,omitempty"`
	SessionId       string   `protobuf:"bytes,9,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FeedbackFor     string   `protobuf:"bytes,10,opt,name=feedback_for,json=feedbackFor,proto3" json:"feedback_for,omitempty"`               // interaction UUID — triggers FEEDBACK strategy
	FeedbackScore   *float64 `protobuf:"fixed64,11,opt,name=feedback_score,json=feedbackScore,proto3,oneof" json:"feedback_score,omitempty"` // -1.0 to 1.0
	FeedbackText    string   `protobuf:"bytes,12,opt,name=feedback_text,json=feedbackText,proto3" json:"feedback_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetStrategies() []string {
	if x != nil {
		return x.Strategies
	}
	return nil
}

func (x *SearchRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *SearchRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *SearchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchRequest) GetNodeSets() []string {
	if x != nil {
		return x.NodeSets
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetSaveInteraction() bool {
	if x != nil {
		return x.SaveInteraction
	}
	return false
}

func (x *SearchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SearchRequest) GetFeedbackFor() string {
	if x != nil {
		return x.FeedbackFor
	}
	return ""
}

func (x *SearchRequest) GetFeedbackScore() float64 {
	if x != nil && x.FeedbackScore != nil {
		return *x.FeedbackScore
	}
	return 0
}

func (x *SearchRequest) GetFeedbackText() string {
	if x != nil {
		return x.FeedbackText
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	InteractionId *string                `protobuf:"bytes,2,opt,name=interaction_id,json=interactionId,proto3,oneof" json:"interaction_id,omitempty"`                                      // [NEW] present when save_interaction=true
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"applied": "true", "affected_nodes": "5"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetInteractionId() string {
	if x != nil && x.InteractionId != nil {
		return *x.InteractionId
	}
	return ""
}

func (x *SearchResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInteractionsRequest) Reset() {
	*x = ListInteractionsRequest{}
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInteractionsRequest) ProtoMessage() {}

func (x *ListInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInteractionsRequest.ProtoReflect.Descriptor instead.
func (*ListInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *ListInteractionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListInteractionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListInteractionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInteractionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type InteractionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	ResultIds     []string               `protobuf:"bytes,4,rep,name=result_ids,json=resultIds,proto3" json:"result_ids,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionInfo) Reset() {
	*x = InteractionInfo{}
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionInfo) ProtoMessage() {}

func (x *InteractionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionInfo.ProtoReflect.Descriptor instead.
func (*InteractionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *InteractionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InteractionInfo) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *InteractionInfo) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *InteractionInfo) GetResultIds() []string {
	if x != nil {
		return x.ResultIds
	}
	return nil
}

func (x *InteractionInfo) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ListInteractionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interactions  []*InteractionInfo     `protobuf:"bytes,1,rep,name=interactions,proto3" json:"interactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInteractionsResponse) Reset() {
	*x = ListInteractionsResponse{}
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInteractionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInteractionsResponse) ProtoMessage() {}

func (x *ListInteractionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cognee_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInteractionsResponse.ProtoReflect.Descriptor instead.
func (*ListInteractionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cognee_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *ListInteractionsResponse) GetInteractions() []*InteractionInfo {
	if x != nil {
		return x.Interactions
	}
	return nil
}

var File_api_proto_cognee_search_v1_search_proto protoreflect.FileDescriptor

const file_api_proto_cognee_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"'api/proto/cognee/search/v1/search.proto\x12\x10cognee.search.v1\"\xa7\x03\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"strategies\x18\x02 \x03(\tR\n" +
	"strategies\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x03 \x01(\tR\tdatasetId\x12!\n" +
	"\fdataset_name\x18\x04 \x01(\tR\vdatasetName\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1b\n" +
	"\tnode_sets\x18\x06 \x03(\tR\bnodeSets\x12\x13\n" +
	"\x05top_k\x18\a \x01(\x05R\x04topK\x12)\n" +
	"\x10save_interaction\x18\b \x01(\bR\x0fsaveInteraction\x12\x1d\n" +
	"\n" +
	"session_id\x18\t \x01(\tR\tsessionId\x12!\n" +
	"\ffeedback_for\x18\n" +
	" \x01(\tR\vfeedbackFor\x12*\n" +
	"\x0efeedback_score\x18\v \x01(\x01H\x00R\rfeedbackScore\x88\x01\x01\x12#\n" +
	"\rfeedback_text\x18\f \x01(\tR\ffeedbackTextB\x11\n" +
	"\x0f_feedback_score\"\xd5\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.cognee.search.v1.SearchResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x02\n" +
	"\x0eSearchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.cognee.search.v1.SearchResultR\aresults\x12*\n" +
	"\x0einteraction_id\x18\x02 \x01(\tH\x00R\rinteractionId\x88\x01\x01\x12J\n" +
	"\bmetadata\x18\x03 \x03(\v2..cognee.search.v1.SearchResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_interaction_id\"\x83\x01\n" +
	"\x17ListInteractionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x90\x01\n" +
	"\x0fInteractionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x1d\n" +
	"\n" +
	"result_ids\x18\x04 \x03(\tR\tresultIds\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"a\n" +
	"\x18ListInteractionsResponse\x12E\n" +
	"\finteractions\x18\x01 \x03(\v2!.cognee.search.v1.InteractionInfoR\finteractions2\xc7\x01\n" +
	"\rSearchService\x12K\n" +
	"\x06Search\x12\x1f.cognee.search.v1.SearchRequest\x1a .cognee.search.v1.SearchResponse\x12i\n" +
	"\x10ListInteractions\x12).cognee.search.v1.ListInteractionsRequest\x1a*.cognee.search.v1.ListInteractionsResponseB2Z0github.com/vnp-memory/api/proto/cognee/search/v1b\x06proto3"

var (
	file_api_proto_cognee_search_v1_search_proto_rawDescOnce sync.Once
	file_api_proto_cognee_search_v1_search_proto_rawDescData []byte
)

func file_api_proto_cognee_search_v1_search_proto_rawDescGZIP() []byte {
	file_api_proto_cognee_search_v1_search_proto_rawDescOnce.Do(func() {
		file_api_proto_cognee_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cognee_search_v1_search_proto_rawDesc), len(file_api_proto_cognee_search_v1_search_proto_rawDesc)))
	})
	return file_api_proto_cognee_search_v1_search_proto_rawDescData
}

var file_api_proto_cognee_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_cognee_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),            // 0: cognee.search.v1.SearchRequest
	(*SearchResult)(nil),             // 1: cognee.search.v1.SearchResult
	(*SearchResponse)(nil),           // 2: cognee.search.v1.SearchResponse
	(*ListInteractionsRequest)(nil),  // 3: cognee.search.v1.ListInteractionsRequest
	(*InteractionInfo)(nil),          // 4: cognee.search.v1.InteractionInfo
	(*ListInteractionsResponse)(nil), // 5: cognee.search.v1.ListInteractionsResponse
	nil,                              // 6: cognee.search.v1.SearchResult.MetadataEntry
	nil,                              // 7: cognee.search.v1.SearchResponse.MetadataEntry
}
var file_api_proto_cognee_search_v1_search_proto_depIdxs = []int32{
	6, // 0: cognee.search.v1.SearchResult.metadata:type_name -> cognee.search.v1.SearchResult.MetadataEntry
	1, // 1: cognee.search.v1.SearchResponse.results:type_name -> cognee.search.v1.SearchResult
	7, // 2: cognee.search.v1.SearchResponse.metadata:type_name -> cognee.search.v1.SearchResponse.MetadataEntry
	4, // 3: cognee.search.v1.ListInteractionsResponse.interactions:type_name -> cognee.search.v1.InteractionInfo
	0, // 4: cognee.search.v1.SearchService.Search:input_type -> cognee.search.v1.SearchRequest
	3, // 5: cognee.search.v1.SearchService.ListInteractions:input_type -> cognee.search.v1.ListInteractionsRequest
	2, // 6: cognee.search.v1.SearchService.Search:output_type -> cognee.search.v1.SearchResponse
	5, // 7: cognee.search.v1.SearchService.ListInteractions:output_type -> cognee.search.v1.ListInteractionsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_cognee_search_v1_search_proto_init() }
func file_api_proto_cognee_search_v1_search_proto_init() {
	if File_api_proto_cognee_search_v1_search_proto != nil {
		return
	}
	file_api_proto_cognee_search_v1_search_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_cognee_search_v1_search_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cognee_search_v1_search_proto_rawDesc), len(file_api_proto_cognee_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cognee_search_v1_search_proto_goTypes,
		DependencyIndexes: file_api_proto_cognee_search_v1_search_proto_depIdxs,
		MessageInfos:      file_api_proto_cognee_search_v1_search_proto_msgTypes,
	}.Build()
	File_api_proto_cognee_search_v1_search_proto = out.File
	file_api_proto_cognee_search_v1_search_proto_goTypes = nil
	file_api_proto_cognee_search_v1_search_proto_depIdxs = nil
}
